import { createContext, useContext } from 'react';

export type AdminLocale = 'it' | 'es';

const it = {
  appName: 'Reception',
  nav: { today: 'Oggi', invites: 'Inviti', history: 'Storico', stats: 'Statistiche', devices: 'Tablet', sites: 'Sedi', hosts: 'Persone da visitare', users: 'Utenti', privacy: 'Privacy', audit: 'Registro accessi', org: 'Organizzazione' },
  navGroups: { visits: 'Visite', setup: 'Configurazione', compliance: 'Privacy e controllo' },
  roles: { SUPER_ADMIN: 'Amministratore', SITE_MANAGER: 'Responsabile di sede', RECEPTIONIST: 'Receptionist', AUDITOR: 'Auditor' },
  status: { OPEN: 'In sede', CLOSED: 'Uscito', AUTO_CLOSED: 'Chiusa d’ufficio', ERASED: 'Cancellata' },
  purposes: { MEETING: 'Riunione', INTERVIEW: 'Colloquio', SUPPLIER: 'Fornitore', MAINTENANCE: 'Manutenzione', DELIVERY: 'Consegna', OTHER: 'Altro' },
  distances: { UNDER_10_KM: 'Meno di 10 km', FROM_10_TO_100_KM: 'Tra 10 e 100 km', OVER_100_KM: 'Più di 100 km' },
  docTypes: { ID_CARD: 'Carta d’identità', PASSPORT: 'Passaporto', DRIVING_LICENSE: 'Patente', OTHER: 'Altro' },
  fileKinds: { SIGNATURE: 'Firma', DOCUMENT: 'Documento', ASSET_IN: 'Seriale PC (ingresso)', ASSET_OUT: 'Seriale PC (uscita)' },
  emailStatus: { NOT_REQUESTED: 'Non richiesta', PENDING: 'In invio', SENT: 'Inviata', FAILED: 'Invio fallito', SKIPPED: 'Email non configurata' },
  org: { email: 'Invio email', emailOn: 'Attivo', emailOff: 'Disattivato', emailFrom: 'Mittente', emailOffHint: 'Il server non ha un SMTP configurato: badge di uscita, informativa e avvisi alla persona da incontrare non vengono inviati, e il tablet non chiede l’email. Chi gestisce il server deve impostare SMTP_HOST e le credenziali nel file .env.', emailTest: 'Invia email di prova', emailSending: 'Invio…', emailSent: 'Email di prova inviata a {to}. Se non arriva, controlla lo spam.', emailFailed: 'Invio non riuscito:', title: 'Organizzazione', intro: 'Nome, logo e colori con cui l’organizzazione compare su tablet, console, pagina di accesso ed email.', uploadLogo: 'Carica logo', changeLogo: 'Cambia logo', colorNames: { '#FFD100': 'Giallo', '#F97316': 'Arancione', '#DC2626': 'Rosso', '#DB2777': 'Fucsia', '#7C3AED': 'Viola', '#2563EB': 'Blu', '#0E7490': 'Petrolio', '#16A34A': 'Verde', '#111111': 'Nero', '#2B2B2B': 'Grafite', '#1F2937': 'Ardesia', '#0F2A44': 'Blu notte', '#123524': 'Verde bosco', '#3B1D2E': 'Prugna' }, name: 'Nome dell’organizzazione', logo: 'Logo', logoHint: 'PNG o JPEG, massimo 200 KB. Meglio su sfondo trasparente.', removeLogo: 'Rimuovi logo', save: 'Salva', saved: 'Salvato.', plan: 'Piano', usage: 'Utilizzo', unlimited: 'illimitati', sites: 'Sedi attive', devices: 'Tablet attivi', users: 'Utenti attivi', address: 'Indirizzo della console', planHint: 'Per aumentare i limiti contatta il fornitore del servizio.', identity: 'Identità', colors: 'Colori', colorsIntro: 'Valgono per tablet, console, pagina di accesso ed email del badge. Il colore del testo si adatta da solo per restare leggibile.', primary: 'Colore principale', primaryHint: 'Pulsanti, selezioni, badge del visitatore e “Sto entrando”.', secondary: 'Colore secondario', secondaryHint: 'Menu della console, pannello di accesso e “Sto uscendo”. Meglio scuro.', custom: 'Personalizzato', reset: 'Ripristina colori predefiniti', preview: 'Anteprima', previewIn: 'Sto entrando', previewOut: 'Sto uscendo', previewBtn: 'Continua', tooSimilar: 'I due colori sono troppo simili: sul tablet le due scelte si distinguono poco.', usage2: 'Piano e utilizzo' },
  addCountry: { title: 'Aggiungi un paese', code: 'Codice paese (ISO, 2 lettere)', name: 'Nome', add: 'Aggiungi paese', hint: 'Il paese parte con impostazioni prudenti e un’informativa da completare con il DPO.' },
  logout: 'Esci', language: 'Lingua',
  login: { tagline: 'Registro visitatori della reception', footnote: 'Dati cifrati, accessi tracciati, cancellazione automatica alla scadenza.', title: 'Accedi alla console', email: 'Email aziendale', password: 'Password', submit: 'Accedi', invalid: 'Email o password non corretti. Dopo 5 tentativi l’account si blocca per 15 minuti.' },
  pwd: { title: 'Imposta una nuova password', intro: 'Al primo accesso, o dopo un reset, devi scegliere una password personale.', current: 'Password attuale', next: 'Nuova password', confirm: 'Ripeti la nuova password', hint: 'Almeno 12 caratteri. Meglio una frase lunga che una parola complicata.', mismatch: 'Le due password non coincidono.', submit: 'Salva password', done: 'Password aggiornata: accedi di nuovo.', wrong: 'La password attuale non è corretta.' },
  site: 'Sede', allSites: 'Tutte le sedi', from: 'Dal', to: 'Al', search: 'Cognome, email o codice', statusLabel: 'Stato', any: 'Tutti',
  visitor: 'Visitatore', company: 'Azienda', host: 'Referente', purpose: 'Motivo', distance: 'Distanza percorsa', checkIn: 'Ingresso', checkOut: 'Uscita', code: 'Codice',
  today: { title: 'Oggi', intro: 'Chi è in sede adesso e gli ingressi di oggi.', present: 'Presenti ora', printList: 'Stampa elenco presenti', noneInside: 'Nessun visitatore in sede.', arrivals: 'Ingressi di oggi', noArrivals: 'Nessun ingresso registrato oggi.', pickSite: 'Scegli una sede per vedere i presenti.', printedAt: 'Elenco generato il', checkoutNow: 'Registra uscita' },
  history: { title: 'Storico visite', intro: 'La ricerca per cognome o email trova solo corrispondenze esatte: i dati sono cifrati.', export: 'Esporta CSV', empty: 'Nessuna visita con questi filtri.', apply: 'Cerca', results: 'risultati', prev: 'Precedenti', next: 'Successivi', receptionistNote: 'Il tuo ruolo vede gli ultimi 7 giorni.' },
  detail: { title: 'Dettaglio visita', email: 'Email', document: 'Documento', notice: 'Informativa accettata', noticeEmail: 'Invio informativa', badgeEmail: 'Invio badge di uscita', hostEmail: 'Avviso al referente', checkOutBy: 'Uscita registrata da', files: 'Immagini', purged: 'Cancellata per scadenza', show: 'Mostra', anonymized: 'Dati personali rimossi il', close: 'Chiudi', erase: 'Cancella dati personali', eraseTitle: 'Cancellazione definitiva', eraseText: 'I dati personali e le immagini di questa visita verranno cancellati in modo irreversibile. Restano solo sede, orari e motivo, senza riferimenti alla persona.', reason: 'Motivo', ticket: 'Riferimento richiesta (senza dati personali)', confirmErase: 'Cancella definitivamente', reasons: { DATA_SUBJECT_REQUEST: 'Richiesta dell’interessato', ENTERED_BY_MISTAKE: 'Inserita per errore', DUPLICATE: 'Duplicato', OTHER: 'Altro' }, audited: 'Ogni apertura di questa scheda e di ogni immagine viene registrata.' },
  devices: { title: 'Tablet', intro: 'Ogni tablet è legato a una sola sede e può essere disattivato in qualsiasi momento.', pair: 'Associa un tablet', name: 'Nome del tablet', namePh: 'Es. Reception piano terra', generate: 'Genera codice', codeIntro: 'Apri /kiosk sul tablet e inserisci questo codice. Vale 15 minuti e una sola volta.', expires: 'Scade alle', lastSeen: 'Ultimo contatto', paired: 'Associato il', revoke: 'Disattiva', revoked: 'Disattivato', active: 'Attivo', confirmRevoke: 'Disattivare questo tablet? Dovrà essere associato di nuovo.', none: 'Nessun tablet associato.' },
  sites: { title: 'Sedi', intro: 'Ogni sede appartiene a un paese, da cui eredita regole privacy e lingue.', add: 'Aggiungi sede', code: 'Codice', name: 'Nome', country: 'Paese', timezone: 'Fuso orario', active: 'Attiva', inactive: 'Non attiva', save: 'Salva sede', deactivate: 'Disattiva', activate: 'Riattiva' },
  hosts: { title: 'Persone da visitare', intro: 'Le persone che i visitatori possono indicare sul tablet. Sul tablet compaiono solo nome, reparto e ruolo. Se indichi l’email, la persona riceve un avviso quando il suo ospite arriva.', add: 'Nuova persona', edit: 'Modifica', firstName: 'Nome', lastName: 'Cognome', department: 'Reparto', jobTitle: 'Ruolo', email: 'Email', phone: 'Telefono', sites: 'Sedi in cui riceve visite', save: 'Salva', cancel: 'Annulla', saved: 'Salvato.', active: 'Attiva', inactive: 'Non attiva', deactivate: 'Disattiva', activate: 'Riattiva', none: 'Nessuna persona censita: il tablet chiede di scrivere il nome del referente.', search: 'Cerca' },
  users: { title: 'Utenti della console', intro: 'Assegna a ogni persona solo il ruolo e le sedi di cui ha bisogno.', person: 'Persona', you: 'tu', search: 'Cerca per nome o email', filters: { active: 'Attivi', inactive: 'Disattivati', all: 'Tutti' }, active: 'Attivo', none: 'Nessun utente in questo elenco.', noResults: 'Nessun utente corrisponde alla ricerca.', details: 'Dati', create: 'Crea utente', pickSite: 'Scegli almeno una sede per questo ruolo.', selfRole: 'Non puoi cambiare il tuo ruolo.', access: 'Accesso', resetHelp: 'Genera una nuova password temporanea; l’utente dovrà cambiarla al primo accesso. Le sessioni aperte vengono chiuse.', deactivateHelp: 'L’utente non potrà più accedere; le sessioni aperte vengono chiuse subito. Lo storico resta.', activateHelp: 'L’utente potrà di nuovo accedere con la sua password.', confirmDeactivate: 'Conferma disattivazione', copy: 'Copia', copied: 'Copiata',  add: 'Nuovo utente', name: 'Nome e cognome', email: 'Email', role: 'Ruolo', sites: 'Sedi', tempPwd: 'Password temporanea', tempPwdHint: 'Almeno 12 caratteri. Comunicala all’utente su un canale diverso dall’email: dovrà cambiarla al primo accesso.', generate: 'Genera', save: 'Salva utente', lastLogin: 'Ultimo accesso', never: 'Mai', resetPwd: 'Reset password', deactivate: 'Disattiva', activate: 'Riattiva', inactive: 'Disattivato', edit: 'Modifica', cancel: 'Annulla', saved: 'Salvato.', roleHelp: { SUPER_ADMIN: 'Configura tutto il sistema, vede tutte le sedi.', SITE_MANAGER: 'Storico completo, export e cancellazioni delle sue sedi; gestisce i tablet.', RECEPTIONIST: 'Presenti e visite degli ultimi 7 giorni delle sue sedi. Nessun export, nessuna immagine.', AUDITOR: 'Sola lettura: registro accessi, tutti i visitatori di tutte le sedi con documenti e immagini, export dello storico.' } },
  privacy: { title: 'Regole privacy per paese', intro: 'I valori sono applicati dal sistema: i dati oltre i termini vengono anonimizzati automaticamente.', retention: 'Conservazione visite (giorni)', docData: 'Chiedi tipo e numero del documento', docPhoto: 'Chiedi foto del documento', docPhotoRet: 'Conservazione foto documento (giorni)', docPhotoIncluded: 'Inclusa sempre quando si chiede il documento.', asset: 'Foto del seriale del PC in ingresso e uscita', assetRet: 'Conservazione foto seriale (giorni)', locales: 'Lingue sul tablet', defaultLocale: 'Lingua predefinita', save: 'Salva regole', saved: 'Regole salvate.', docPhotoWarn: 'Fotografare i documenti d’identità va giustificato: valuta con il DPO se il numero del documento non è sufficiente.', notices: 'Informative', noticeIntro: 'Ogni salvataggio crea una nuova versione. Le visite già registrate restano legate al testo che hanno accettato.', version: 'Versione', publish: 'Pubblica nuova versione', noticeTitle: 'Titolo', noticeBody: 'Testo', placeholderHint: 'Usa {{visitRetentionDays}} per inserire automaticamente i giorni di conservazione.', published: 'Pubblicata la versione', readOnly: 'Solo lettura per il tuo ruolo.' },
  invites: { title: 'Inviti', intro: 'Registra in anticipo chi è atteso: l’ospite riceve un’email con un QR e all’arrivo lo mostra al tablet, che compila i dati da solo. Deve solo leggere l’informativa e firmare.', add: 'Nuovo invito', send: 'Crea e invia', show: 'Mostra', upcoming: 'Da oggi in poi', past: 'Passati', site: 'Sede', host: 'Chi incontra', pickHost: 'Scegli la persona', noHosts: 'Nessuna persona in questa sede: aggiungila in Persone da visitare', date: 'Giorno', time: 'Ora prevista', timeHint: 'Ora della sede ({tz}).', guest: 'Ospite', company: 'Azienda', purpose: 'Motivo', emailHint: 'Riceverà qui l’invito con il QR.', when: 'Quando', status: 'Stato', emailCol: 'Email', statuses: { PENDING: 'Atteso', USED: 'Arrivato', CANCELLED: 'Annullato', EXPIRED: 'Non presentato' }, emailStatuses: { PENDING: 'In invio', SENT: 'Inviata', FAILED: 'Non riuscita', SKIPPED: 'Non inviata', NOT_REQUESTED: '—' }, showQr: 'QR', resend: 'Reinvia', cancel: 'Annulla invito', cancelConfirm: 'Annullare l’invito di {name}? Il QR smetterà di funzionare.', cancelled: 'Invito annullato.', resent: 'L’invito verrà reinviato a {email} entro un minuto.', created: 'Invito creato: l’email con il QR parte entro un minuto.', createdNoEmail: 'Invito creato, ma l’invio email non è attivo: apri il QR e mandalo all’ospite in altro modo.', noneUpcoming: 'Nessun ospite atteso. Crea un invito per chi deve arrivare nei prossimi giorni.', nonePast: 'Nessun invito negli ultimi 7 giorni.', qrHint: 'L’ospite può mostrare questo QR al tablet oppure fotografarlo. Vale solo nel giorno previsto e in questa sede, una sola volta.' },
  stats: { title: 'Statistiche', intro: 'Numeri aggregati sulle visite: nessun visitatore è riconoscibile. Restano validi anche dopo l’anonimizzazione.', period: 'Periodo', lastDays: 'Ultimi {n} giorni', custom: 'Personalizzato', visits: 'Visite', perDay: 'Media al giorno', duration: 'Durata tipica', durationHint: 'mediana · media {avg}', peak: 'Ora di punta', perDayChart: 'Visite al giorno', byHour: 'Arrivi per ora', byWeekday: 'Visite per giorno della settimana', byPurpose: 'Motivo della visita', byDistance: 'Distanza percorsa', bySite: 'Visite per sede', notAsked: 'Non rilevata', showData: 'Mostra i dati', day: 'Giorno', hour: 'Fascia oraria', weekday: 'Giorno', empty: 'Nessuna visita nel periodo scelto.', footnote: 'Orari nel fuso di ciascuna sede. La durata considera solo le uscite registrate, non le chiusure automatiche.' },
  audit: { title: 'Registro accessi', intro: 'Chi ha fatto cosa, quando e da dove. Il registro non si può modificare né cancellare dalla console.', when: 'Quando', actor: 'Chi', action: 'Azione', target: 'Oggetto', ip: 'IP', details: 'Dettagli', filterAction: 'Azione', filterActor: 'Utente o tablet', export: 'Esporta CSV' },
  errors: { INVALID_DATE: 'Data non valida.', INVITATION_IN_PAST: 'Il giorno scelto è già passato.', INVITATION_TOO_FAR: 'Si può invitare al massimo 90 giorni prima.', HOST_NOT_FOUND: 'La persona scelta non riceve visite in questa sede.', INVITATION_USED: 'L’ospite è già arrivato con questo invito.', INVITATION_CANCELLED: 'L’invito è stato annullato.', INVITATION_EXPIRED: 'Il giorno dell’invito è passato.', EMAIL_DISABLED: 'L’invio email non è attivo: vedi Organizzazione.', generic: 'Operazione non riuscita. Riprova.', forbidden: 'Il tuo ruolo non consente questa operazione.', EMAIL_EXISTS: 'Esiste già un utente con questa email.', SITE_CODE_EXISTS: 'Esiste già una sede con questo codice.', INVALID_TIMEZONE: 'Fuso orario non valido (es. Europe/Rome).', EXPORT_TOO_LARGE: 'Troppi risultati: restringi il periodo (massimo 10.000 righe).', CANNOT_DEMOTE_SELF: 'Non puoi togliere a te stesso il ruolo di amministratore.', DEFAULT_LOCALE_NOT_ENABLED: 'La lingua predefinita deve essere tra quelle attive.', PLAN_LIMIT_SITES: 'Hai raggiunto il numero massimo di sedi previsto dal tuo piano.', PLAN_LIMIT_DEVICES: 'Hai raggiunto il numero massimo di tablet previsto dal tuo piano.', PLAN_LIMIT_USERS: 'Hai raggiunto il numero massimo di utenti previsto dal tuo piano.', COUNTRY_EXISTS: 'Questo paese è già configurato.', UNKNOWN_COUNTRY: 'Configura prima il paese nella sezione Privacy.', TENANT_SUSPENDED: 'L’accesso di questa organizzazione è sospeso. Contatta il fornitore del servizio.', HOST_SITE_REQUIRED: 'Scegli almeno una sede.' },
};
type Dict = typeof it;

const es: Dict = {
  appName: 'Recepción',
  nav: { today: 'Hoy', invites: 'Invitaciones', history: 'Historial', stats: 'Estadísticas', devices: 'Tabletas', sites: 'Sedes', hosts: 'Personas a visitar', users: 'Usuarios', privacy: 'Privacidad', audit: 'Registro de accesos', org: 'Organización' },
  navGroups: { visits: 'Visitas', setup: 'Configuración', compliance: 'Privacidad y control' },
  roles: { SUPER_ADMIN: 'Administrador', SITE_MANAGER: 'Responsable de sede', RECEPTIONIST: 'Recepcionista', AUDITOR: 'Auditor' },
  status: { OPEN: 'En la sede', CLOSED: 'Salió', AUTO_CLOSED: 'Cerrada de oficio', ERASED: 'Suprimida' },
  purposes: { MEETING: 'Reunión', INTERVIEW: 'Entrevista', SUPPLIER: 'Proveedor', MAINTENANCE: 'Mantenimiento', DELIVERY: 'Entrega', OTHER: 'Otro' },
  distances: { UNDER_10_KM: 'Menos de 10 km', FROM_10_TO_100_KM: 'Entre 10 y 100 km', OVER_100_KM: 'Más de 100 km' },
  docTypes: { ID_CARD: 'DNI / Cédula', PASSPORT: 'Pasaporte', DRIVING_LICENSE: 'Licencia de conducir', OTHER: 'Otro' },
  fileKinds: { SIGNATURE: 'Firma', DOCUMENT: 'Documento', ASSET_IN: 'Serie del portátil (entrada)', ASSET_OUT: 'Serie del portátil (salida)' },
  emailStatus: { NOT_REQUESTED: 'No solicitado', PENDING: 'Enviando', SENT: 'Enviado', FAILED: 'Error de envío', SKIPPED: 'Correo no configurado' },
  org: { email: 'Envío de correo', emailOn: 'Activo', emailOff: 'Desactivado', emailFrom: 'Remitente', emailOffHint: 'El servidor no tiene SMTP configurado: no se envían la credencial de salida, la información de privacidad ni los avisos a la persona visitada, y la tableta no pide el correo. Quien gestiona el servidor debe configurar SMTP_HOST y las credenciales en el archivo .env.', emailTest: 'Enviar correo de prueba', emailSending: 'Enviando…', emailSent: 'Correo de prueba enviado a {to}. Si no llega, revise el spam.', emailFailed: 'Envío fallido:', title: 'Organización', intro: 'Nombre, logotipo y colores con los que la organización aparece en la tableta, la consola, la página de acceso y los correos.', uploadLogo: 'Subir logotipo', changeLogo: 'Cambiar logotipo', colorNames: { '#FFD100': 'Amarillo', '#F97316': 'Naranja', '#DC2626': 'Rojo', '#DB2777': 'Fucsia', '#7C3AED': 'Violeta', '#2563EB': 'Azul', '#0E7490': 'Petróleo', '#16A34A': 'Verde', '#111111': 'Negro', '#2B2B2B': 'Grafito', '#1F2937': 'Pizarra', '#0F2A44': 'Azul noche', '#123524': 'Verde bosque', '#3B1D2E': 'Ciruela' }, name: 'Nombre de la organización', logo: 'Logotipo', logoHint: 'PNG o JPEG, máximo 200 KB. Mejor con fondo transparente.', removeLogo: 'Quitar logotipo', save: 'Guardar', saved: 'Guardado.', plan: 'Plan', usage: 'Uso', unlimited: 'ilimitados', sites: 'Sedes activas', devices: 'Tabletas activas', users: 'Usuarios activos', address: 'Dirección de la consola', planHint: 'Para ampliar los límites contacte con el proveedor del servicio.', identity: 'Identidad', colors: 'Colores', colorsIntro: 'Se aplican a la tableta, la consola, la página de acceso y el correo de la credencial. El color del texto se ajusta solo para seguir siendo legible.', primary: 'Color principal', primaryHint: 'Botones, selecciones, credencial del visitante y «Estoy entrando».', secondary: 'Color secundario', secondaryHint: 'Menú de la consola, panel de acceso y «Estoy saliendo». Mejor oscuro.', custom: 'Personalizado', reset: 'Restablecer colores predeterminados', preview: 'Vista previa', previewIn: 'Estoy entrando', previewOut: 'Estoy saliendo', previewBtn: 'Continuar', tooSimilar: 'Los dos colores son demasiado parecidos: en la tableta las dos opciones se distinguen poco.', usage2: 'Plan y uso' },
  addCountry: { title: 'Añadir un país', code: 'Código de país (ISO, 2 letras)', name: 'Nombre', add: 'Añadir país', hint: 'El país empieza con valores prudentes y un texto informativo que debe completar con el DPO.' },
  logout: 'Salir', language: 'Idioma',
  login: { tagline: 'Registro de visitantes de recepción', footnote: 'Datos cifrados, accesos registrados, supresión automática al vencer el plazo.', title: 'Acceder a la consola', email: 'Correo corporativo', password: 'Contraseña', submit: 'Acceder', invalid: 'Correo o contraseña incorrectos. Tras 5 intentos la cuenta se bloquea 15 minutos.' },
  pwd: { title: 'Defina una nueva contraseña', intro: 'En el primer acceso, o tras un restablecimiento, debe elegir una contraseña personal.', current: 'Contraseña actual', next: 'Nueva contraseña', confirm: 'Repita la nueva contraseña', hint: 'Al menos 12 caracteres. Mejor una frase larga que una palabra complicada.', mismatch: 'Las contraseñas no coinciden.', submit: 'Guardar contraseña', done: 'Contraseña actualizada: vuelva a acceder.', wrong: 'La contraseña actual no es correcta.' },
  site: 'Sede', allSites: 'Todas las sedes', from: 'Desde', to: 'Hasta', search: 'Apellido, correo o código', statusLabel: 'Estado', any: 'Todos',
  visitor: 'Visitante', company: 'Empresa', host: 'Contacto', purpose: 'Motivo', distance: 'Distancia recorrida', checkIn: 'Entrada', checkOut: 'Salida', code: 'Código',
  today: { title: 'Hoy', intro: 'Quién está en la sede ahora y las entradas de hoy.', present: 'Presentes ahora', printList: 'Imprimir lista de presentes', noneInside: 'No hay visitantes en la sede.', arrivals: 'Entradas de hoy', noArrivals: 'No hay entradas registradas hoy.', pickSite: 'Elija una sede para ver los presentes.', printedAt: 'Lista generada el', checkoutNow: 'Registrar salida' },
  history: { title: 'Historial de visitas', intro: 'La búsqueda por apellido o correo solo encuentra coincidencias exactas: los datos están cifrados.', export: 'Exportar CSV', empty: 'No hay visitas con estos filtros.', apply: 'Buscar', results: 'resultados', prev: 'Anteriores', next: 'Siguientes', receptionistNote: 'Su rol ve los últimos 7 días.' },
  detail: { title: 'Detalle de la visita', email: 'Correo', document: 'Documento', notice: 'Información aceptada', noticeEmail: 'Envío de la información', badgeEmail: 'Envío de la credencial de salida', hostEmail: 'Aviso al contacto', checkOutBy: 'Salida registrada por', files: 'Imágenes', purged: 'Eliminada por vencimiento', show: 'Mostrar', anonymized: 'Datos personales eliminados el', close: 'Cerrar', erase: 'Suprimir datos personales', eraseTitle: 'Supresión definitiva', eraseText: 'Los datos personales y las imágenes de esta visita se eliminarán de forma irreversible. Solo quedan sede, horario y motivo, sin referencia a la persona.', reason: 'Motivo', ticket: 'Referencia de la solicitud (sin datos personales)', confirmErase: 'Suprimir definitivamente', reasons: { DATA_SUBJECT_REQUEST: 'Solicitud del titular', ENTERED_BY_MISTAKE: 'Registrada por error', DUPLICATE: 'Duplicado', OTHER: 'Otro' }, audited: 'Cada apertura de esta ficha y de cada imagen queda registrada.' },
  devices: { title: 'Tabletas', intro: 'Cada tableta está vinculada a una sola sede y puede desactivarse en cualquier momento.', pair: 'Vincular una tableta', name: 'Nombre de la tableta', namePh: 'Ej. Recepción planta baja', generate: 'Generar código', codeIntro: 'Abra /kiosk en la tableta e introduzca este código. Vale 15 minutos y un solo uso.', expires: 'Caduca a las', lastSeen: 'Último contacto', paired: 'Vinculada el', revoke: 'Desactivar', revoked: 'Desactivada', active: 'Activa', confirmRevoke: '¿Desactivar esta tableta? Deberá vincularse de nuevo.', none: 'No hay tabletas vinculadas.' },
  sites: { title: 'Sedes', intro: 'Cada sede pertenece a un país, del que hereda las reglas de privacidad y los idiomas.', add: 'Añadir sede', code: 'Código', name: 'Nombre', country: 'País', timezone: 'Zona horaria', active: 'Activa', inactive: 'Inactiva', save: 'Guardar sede', deactivate: 'Desactivar', activate: 'Reactivar' },
  hosts: { title: 'Personas a visitar', intro: 'Las personas que los visitantes pueden indicar en la tableta. En la tableta solo aparecen nombre, departamento y cargo. Si indica el correo, la persona recibe un aviso cuando llega su visita.', add: 'Nueva persona', edit: 'Editar', firstName: 'Nombre', lastName: 'Apellidos', department: 'Departamento', jobTitle: 'Cargo', email: 'Correo', phone: 'Teléfono', sites: 'Sedes en las que recibe visitas', save: 'Guardar', cancel: 'Cancelar', saved: 'Guardado.', active: 'Activa', inactive: 'Inactiva', deactivate: 'Desactivar', activate: 'Reactivar', none: 'No hay personas registradas: la tableta pide escribir el nombre del contacto.', search: 'Buscar' },
  users: { title: 'Usuarios de la consola', intro: 'Asigne a cada persona solo el rol y las sedes que necesita.', person: 'Persona', you: 'usted', search: 'Buscar por nombre o correo', filters: { active: 'Activos', inactive: 'Desactivados', all: 'Todos' }, active: 'Activo', none: 'No hay usuarios en esta lista.', noResults: 'Ningún usuario coincide con la búsqueda.', details: 'Datos', create: 'Crear usuario', pickSite: 'Elija al menos una sede para este rol.', selfRole: 'No puede cambiar su propio rol.', access: 'Acceso', resetHelp: 'Genera una nueva contraseña temporal; el usuario deberá cambiarla en el primer acceso. Las sesiones abiertas se cierran.', deactivateHelp: 'El usuario ya no podrá acceder; las sesiones abiertas se cierran de inmediato. El historial se conserva.', activateHelp: 'El usuario podrá volver a acceder con su contraseña.', confirmDeactivate: 'Confirmar desactivación', copy: 'Copiar', copied: 'Copiada',  add: 'Nuevo usuario', name: 'Nombre y apellidos', email: 'Correo', role: 'Rol', sites: 'Sedes', tempPwd: 'Contraseña temporal', tempPwdHint: 'Al menos 12 caracteres. Comuníquela por un canal distinto del correo: deberá cambiarla en el primer acceso.', generate: 'Generar', save: 'Guardar usuario', lastLogin: 'Último acceso', never: 'Nunca', resetPwd: 'Restablecer contraseña', deactivate: 'Desactivar', activate: 'Reactivar', inactive: 'Desactivado', edit: 'Editar', cancel: 'Cancelar', saved: 'Guardado.', roleHelp: { SUPER_ADMIN: 'Configura todo el sistema y ve todas las sedes.', SITE_MANAGER: 'Historial completo, exportación y supresiones de sus sedes; gestiona las tabletas.', RECEPTIONIST: 'Presentes y visitas de los últimos 7 días de sus sedes. Sin exportación ni imágenes.', AUDITOR: 'Solo lectura: registro de accesos, todos los visitantes de todas las sedes con documentos e imágenes, exportación del historial.' } },
  privacy: { title: 'Reglas de privacidad por país', intro: 'El sistema aplica estos valores: los datos que superan los plazos se anonimizan automáticamente.', retention: 'Conservación de visitas (días)', docData: 'Pedir tipo y número de documento', docPhoto: 'Pedir foto del documento', docPhotoRet: 'Conservación foto documento (días)', docPhotoIncluded: 'Incluida siempre cuando se pide el documento.', asset: 'Foto del número de serie del portátil en entrada y salida', assetRet: 'Conservación foto de serie (días)', locales: 'Idiomas en la tableta', defaultLocale: 'Idioma predeterminado', save: 'Guardar reglas', saved: 'Reglas guardadas.', docPhotoWarn: 'Fotografiar documentos de identidad debe estar justificado: valore con el DPO si el número de documento no es suficiente.', notices: 'Textos informativos', noticeIntro: 'Cada guardado crea una nueva versión. Las visitas ya registradas siguen vinculadas al texto que aceptaron.', version: 'Versión', publish: 'Publicar nueva versión', noticeTitle: 'Título', noticeBody: 'Texto', placeholderHint: 'Use {{visitRetentionDays}} para insertar automáticamente los días de conservación.', published: 'Publicada la versión', readOnly: 'Solo lectura para su rol.' },
  invites: { title: 'Invitaciones', intro: 'Registre con antelación a quien se espera: el invitado recibe un correo con un QR y al llegar lo muestra a la tableta, que completa los datos sola. Solo debe leer la información de privacidad y firmar.', add: 'Nueva invitación', send: 'Crear y enviar', show: 'Mostrar', upcoming: 'De hoy en adelante', past: 'Pasadas', site: 'Sede', host: 'A quién visita', pickHost: 'Elija la persona', noHosts: 'No hay personas en esta sede: agréguelas en Personas a visitar', date: 'Día', time: 'Hora prevista', timeHint: 'Hora de la sede ({tz}).', guest: 'Invitado', company: 'Empresa', purpose: 'Motivo', emailHint: 'Recibirá aquí la invitación con el QR.', when: 'Cuándo', status: 'Estado', emailCol: 'Correo', statuses: { PENDING: 'Esperado', USED: 'Llegó', CANCELLED: 'Anulada', EXPIRED: 'No se presentó' }, emailStatuses: { PENDING: 'Enviando', SENT: 'Enviado', FAILED: 'Fallido', SKIPPED: 'No enviado', NOT_REQUESTED: '—' }, showQr: 'QR', resend: 'Reenviar', cancel: 'Anular', cancelConfirm: '¿Anular la invitación de {name}? El QR dejará de funcionar.', cancelled: 'Invitación anulada.', resent: 'La invitación se reenviará a {email} en un minuto.', created: 'Invitación creada: el correo con el QR sale en un minuto.', createdNoEmail: 'Invitación creada, pero el envío de correo no está activo: abra el QR y envíelo al invitado por otro medio.', noneUpcoming: 'No hay invitados esperados. Cree una invitación para quien llegue en los próximos días.', nonePast: 'No hay invitaciones en los últimos 7 días.', qrHint: 'El invitado puede mostrar este QR a la tableta o fotografiarlo. Vale solo el día previsto, en esta sede y una sola vez.' },
  stats: { title: 'Estadísticas', intro: 'Cifras agregadas de las visitas: ningún visitante es identificable. Siguen siendo válidas tras la anonimización.', period: 'Periodo', lastDays: 'Últimos {n} días', custom: 'Personalizado', visits: 'Visitas', perDay: 'Media diaria', duration: 'Duración típica', durationHint: 'mediana · media {avg}', peak: 'Hora punta', perDayChart: 'Visitas por día', byHour: 'Llegadas por hora', byWeekday: 'Visitas por día de la semana', byPurpose: 'Motivo de la visita', byDistance: 'Distancia recorrida', bySite: 'Visitas por sede', notAsked: 'No registrada', showData: 'Mostrar los datos', day: 'Día', hour: 'Franja horaria', weekday: 'Día', empty: 'No hay visitas en el periodo elegido.', footnote: 'Horas en la zona horaria de cada sede. La duración considera solo las salidas registradas, no los cierres automáticos.' },
  audit: { title: 'Registro de accesos', intro: 'Quién hizo qué, cuándo y desde dónde. El registro no puede modificarse ni borrarse desde la consola.', when: 'Cuándo', actor: 'Quién', action: 'Acción', target: 'Objeto', ip: 'IP', details: 'Detalles', filterAction: 'Acción', filterActor: 'Usuario o tableta', export: 'Exportar CSV' },
  errors: { INVALID_DATE: 'Fecha no válida.', INVITATION_IN_PAST: 'El día elegido ya pasó.', INVITATION_TOO_FAR: 'Se puede invitar como máximo con 90 días de antelación.', HOST_NOT_FOUND: 'La persona elegida no recibe visitas en esta sede.', INVITATION_USED: 'El invitado ya llegó con esta invitación.', INVITATION_CANCELLED: 'La invitación fue anulada.', INVITATION_EXPIRED: 'El día de la invitación ya pasó.', EMAIL_DISABLED: 'El envío de correo no está activo: vea Organización.', generic: 'No se pudo completar la operación. Inténtelo de nuevo.', forbidden: 'Su rol no permite esta operación.', EMAIL_EXISTS: 'Ya existe un usuario con este correo.', SITE_CODE_EXISTS: 'Ya existe una sede con este código.', INVALID_TIMEZONE: 'Zona horaria no válida (ej. America/Lima).', EXPORT_TOO_LARGE: 'Demasiados resultados: acote el periodo (máximo 10.000 filas).', CANNOT_DEMOTE_SELF: 'No puede quitarse a sí mismo el rol de administrador.', DEFAULT_LOCALE_NOT_ENABLED: 'El idioma predeterminado debe estar entre los activos.', PLAN_LIMIT_SITES: 'Ha alcanzado el número máximo de sedes de su plan.', PLAN_LIMIT_DEVICES: 'Ha alcanzado el número máximo de tabletas de su plan.', PLAN_LIMIT_USERS: 'Ha alcanzado el número máximo de usuarios de su plan.', COUNTRY_EXISTS: 'Este país ya está configurado.', UNKNOWN_COUNTRY: 'Configure antes el país en la sección Privacidad.', TENANT_SUSPENDED: 'El acceso de esta organización está suspendido. Contacte con el proveedor del servicio.', HOST_SITE_REQUIRED: 'Elija al menos una sede.' },
};

export const ADMIN_STRINGS: Record<AdminLocale, Dict> = { it, es };
export type AdminStrings = Dict;

export const I18nContext = createContext<{ t: AdminStrings; locale: AdminLocale; intl: string; setLocale: (l: AdminLocale) => void }>({ t: it, locale: 'it', intl: 'it-IT', setLocale: () => {} });
export const useI18n = () => useContext(I18nContext);

export function errorText(t: AdminStrings, e: unknown): string {
  const code = (e as { code?: string })?.code;
  const status = (e as { status?: number })?.status;
  if (code && code in t.errors) return t.errors[code as keyof AdminStrings['errors']];
  if (status === 403) return t.errors.forbidden;
  return t.errors.generic;
}
