/**
 * Texts of the "My badge" page: the same as the phone app (mobile/src/lib/i18n.ts), so the two read
 * alike. Only what differs on the web is changed: notifications go through the browser, and there is
 * no organisation step (the page is already on the organisation's address).
 */
const STRINGS = {
  it: {
    title: 'Il mio badge',
    orgTitle: 'La tua organizzazione',
    orgIntro: 'Scrivi l’indirizzo della console della tua azienda (quello che apri nel browser per accedere): lo trovi nell’email di benvenuto o chiedilo all’ufficio del personale.',
    orgLabel: 'Indirizzo', orgExample: 'es. https://azienda.esempio.it',
    orgNext: 'Continua',
    orgInvalid: 'Indirizzo non valido: deve iniziare con https:// oppure essere del tipo azienda.esempio.it.',
    orgUnreachable: 'Non trovo un’organizzazione a questo indirizzo. Controlla e riprova.',
    emailIntro: 'Attiva il badge con la tua email di lavoro: ti mandiamo un codice.',
    email: 'Email di lavoro',
    send: 'Inviami il codice',
    sent: 'Se l’indirizzo è registrato, ricevi un codice di 6 cifre entro un minuto. Controlla anche lo spam.',
    code: 'Codice ricevuto',
    activate: 'Attiva il badge',
    changeEmail: 'Cambia email',
    changeOrg: 'Cambia organizzazione',
    hint: 'Mostra il QR al lettore della porta. Cambia ogni 30 secondi: foto e screenshot non funzionano.',
    next: 'Nuovo codice tra {n} s',
    remove: 'Rimuovi il badge da questo telefono',
    removeTitle: 'Rimuovere il badge?',
    removeText: 'Per usarlo di nuovo dovrai chiedere un nuovo codice via email.',
    removeConfirm: 'Rimuovi',
    cancel: 'Annulla',
    nfcReady: 'Oppure avvicina il retro del telefono al lettore, come una tessera.',
    nfcOff: 'Per usare il telefono come tessera attiva l’NFC.',
    nfcOpen: 'Attiva NFC',
    nfcDevBuild: 'Il telefono come tessera NFC funziona nell’app installata, non in Expo Go.',
    ssoSignIn: 'Accedi con {provider}', ssoOr: 'oppure ricevi un codice via email', ssoHint: 'Usa l’account aziendale con cui entri in Outlook, Teams o Gmail.',
    activated: 'Badge attivo su questo telefono.', loading: 'Caricamento…',
    clock: 'L’ora del telefono sembra sbagliata: attiva data e ora automatiche, altrimenti il lettore rifiuta il QR.',
    parcels: { one: 'Un pacco ti aspetta in reception', many: '{n} pacchi ti aspettano in reception', today: '{site} · arrivato alle {time}', day: '{site} · arrivato il {date}', pieces: '{n} colli' },
    settings: { open: 'Impostazioni', title: 'Impostazioni', back: 'Indietro', org: 'Organizzazione', person: 'Intestato a', address: 'Indirizzo', removeIntro: 'Togli il badge se cambi telefono o lo restituisci. Smette di funzionare subito, anche sul server.', locked: 'La tua organizzazione gestisce il badge dalla console. Se cambi o perdi il telefono, chiedi all’amministratore di disattivarlo.', revoked: 'Questo badge non è più valido: è stato disattivato dalla console. Toglilo da qui e attivalo di nuovo.', offline: 'Non riesco a contattare il server. Riprova quando sei connesso.', retry: 'Riprova', SELF_REMOVE_DISABLED: 'La tua organizzazione non permette più di togliere il badge da qui: chiedi all’amministratore.' },
    stale: { title: 'Questo badge non è più valido', text: 'È stato attivato su un altro dispositivo oppure disattivato dalla console, e il lettore della porta lo rifiuta. Attivalo di nuovo su questo telefono.', old: 'Questo badge è stato attivato con una versione precedente: per pacchi e inviti attivalo di nuovo.', action: 'Attiva di nuovo', offline: 'Non riesco a contattare il server: pacchi e inviti potrebbero non essere aggiornati. Il QR funziona lo stesso.' },
    portal: { title: 'Le tue app', badge: 'Badge', home: 'Inizio', invites: 'Inviti', invitesDetail: 'Ospiti attesi e nuovi inviti', parcels: 'Pacchi', parcelsNone: 'Niente da ritirare', parcelsSome: '{n} da ritirare', noBadge: 'Il badge per le porte non è attivo per te. Le altre app della tua organizzazione sono nella barra in basso.', parcelsEmpty: 'Non ci sono pacchi da ritirare. Quando ne arriva uno ricevi un avviso.' },
    parking: { title: 'Parcheggio', tile: 'Parcheggio', tileDetail: 'I tuoi giorni e le prenotazioni', fixed: 'Il tuo posto fisso: {spot}', fixedHint: 'Ogni lunedì è prenotato per te tutta la settimana dopo. Se un giorno non vieni, liberalo: lo può prendere un collega.', userHint: 'Prenota i giorni che ti servono, al massimo {n} alla volta. La settimana dopo si apre il giovedì.', opens: 'La settimana prossima si apre {date}.', active: 'Prenotazioni attive: {n} su {max}', book: 'Prenota', free: '{n} liberi', full: 'Completo', notOpen: 'Si apre giovedì', spot: 'Posto {spot}', auto: 'fisso', release: 'Libera', cancel: 'Annulla', releaseTitle: 'Liberare il posto?', releaseText: 'Il posto diventa libero per i colleghi.', today: 'Oggi', tomorrow: 'Domani', none: 'Nessun posto auto configurato: chiedi all’amministratore.', booked: 'Prenotato: posto {spot}.', pick: 'Scegli i giorni', pickHint: 'Tocca i giorni che ti servono, poi scegli il posto. Tocca un giorno già prenotato per liberarlo.', thisWeek: 'Questa settimana', nextWeek: 'Settimana prossima', spotTitle: 'Posto', anySpot: 'Il primo libero', anySpotHint: 'Assegnato in automatico, giorno per giorno.', noCommonSpot: 'Nessun posto è libero in tutti i giorni scelti: prenota con il primo libero.', bookOne: 'Prenota 1 giorno', bookMany: 'Prenota {n} giorni', clear: 'Annulla selezione', bookedDays: 'Prenotato: {list}.', dayOn: '{day}, posto {spot}', failedDay: '{day}: {reason}', leftOne: 'Puoi prenotare ancora 1 giorno.', leftMany: 'Puoi prenotare ancora {n} giorni.', closed: 'Chiuso', selected: 'selezionato', errors: { PARKING_SPOT_TAKEN: 'Quel posto è già preso quel giorno.', PARKING_SPOT_NOT_FOUND: 'Quel posto non è più disponibile.', PARKING_LIMIT: 'Hai già 4 prenotazioni attive: annullane una per prenotare un altro giorno.', PARKING_FULL: 'Quel giorno è tutto occupato.', PARKING_ALREADY_BOOKED: 'Hai già un posto quel giorno.', PARKING_DAY_CLOSED: 'Quel giorno non si può ancora prenotare.', PARKING_DAY_PAST: 'Quel giorno è già passato.', NO_PARKING: 'Il parcheggio non è attivo per te.', APP_DISABLED: 'Il parcheggio non è attivo per la tua organizzazione.' } },
    invites: {
      open: 'I miei inviti', title: 'Inviti', back: 'Indietro', new: 'Nuovo invito', none: 'Nessun ospite atteso. Crea un invito: l’ospite riceve un’email con un QR e alla reception tocca “Ho un invito”.',
      today: 'Oggi', tomorrow: 'Domani', refresh: 'Aggiorna',
      guest: 'Ospite', firstName: 'Nome', lastName: 'Cognome', company: 'Azienda (facoltativo)', email: 'Email dell’ospite',
      when: 'Quando', day: 'Giorno', time: 'Ora', timeHint: 'Per esempio 9:30', site: 'Sede', purpose: 'Motivo',
      create: 'Crea invito', created: 'Invito creato.',
      emailSent: 'L’ospite riceve un’email con il QR. Puoi anche mandargli tu il codice.',
      emailOff: 'L’invio email non è attivo: manda tu il codice all’ospite.',
      code: 'Codice', share: 'Condividi con l’ospite', copied: 'Testo copiato: incollalo in un messaggio.', cancel: 'Annulla invito', cancelTitle: 'Annullare l’invito?', cancelText: 'Il codice smette di funzionare. Se l’ospite ha già l’email, avvisalo tu.', cancelConfirm: 'Annulla invito', keep: 'Tieni',
      status: { PENDING: 'Atteso', USED: 'Arrivato', CANCELLED: 'Annullato', EXPIRED: 'Non arrivato' },
      purposes: { MEETING: 'Riunione', INTERVIEW: 'Colloquio', SUPPLIER: 'Fornitore', MAINTENANCE: 'Manutenzione', DELIVERY: 'Consegna', OTHER: 'Altro' },
      shareText: 'Ciao {firstName}, ti aspetto {when} da {organisation}, sede di {site}. All’arrivo tocca “Ho un invito” sul tablet della reception e mostra il QR dell’email, oppure scrivi il codice {code}. A presto, {host}',
      push: { label: 'Avvisami quando arriva un ospite', hint: 'Una notifica su questo telefono quando un tuo ospite fa check-in al tablet della reception.', denied: 'Il browser blocca le notifiche di questo sito: sbloccale dalle impostazioni del sito, poi riprova.', unsupported: 'Questo browser non riceve notifiche dalle pagine web. Prova con Chrome, oppure usa l’app Il mio badge.', ios: 'Su iPhone le notifiche arrivano solo dalla schermata Home: tocca Condividi → Aggiungi alla schermata Home, apri il badge da lì e attivale.', test: 'Manda una prova', testSent: 'Prova inviata: arriva tra pochi secondi.' },
      reactivate: 'Per invitare ospiti da qui rimuovi il badge e attivalo di nuovo: serve una sola volta.',
      errors: { BAD_RESPONSE: 'Il server ha risposto in modo inatteso. Controlla l’indirizzo dell’organizzazione e la connessione, poi riprova.', name: 'Scrivi nome e cognome, solo lettere.', email: 'Email non valida.', time: 'Ora non valida: per esempio 9:30.', INVITATION_IN_PAST: 'Quel giorno è già passato.', INVITATION_TOO_FAR: 'Puoi invitare fino a 90 giorni in anticipo.', NOT_A_HOST: 'Non sei più tra le persone da visitare: chiedi alla reception.', NOT_A_HOST_HERE: 'In questa sede non ricevi visite.', INVITATION_USED: 'L’ospite è già arrivato.', INVITATION_CANCELLED: 'Invito già annullato.', INVITATION_EXPIRED: 'Invito scaduto.' },
    },
    errors: { CANCELLED: 'Accesso annullato.', NO_EMPLOYEE: 'Il tuo account aziendale non risulta tra i dipendenti con badge: chiedi all’ufficio del personale.', OTHER_DIRECTORY: 'Hai usato l’account di un’altra organizzazione.', WRONG_ISSUER: 'Hai usato l’account di un’altra organizzazione.', NOT_A_WORK_ACCOUNT: 'Serve l’account di lavoro, non uno personale.', PROVIDER_REFUSED: 'L’accesso è stato rifiutato. Riprova; se succede ancora, chiedi all’IT.', PROVIDER_UNREACHABLE: 'Il servizio di accesso non risponde. Riprova tra poco.', SSO_NOT_CONFIGURED: 'La tua organizzazione non ha attivato l’accesso con l’account aziendale: usa il codice via email.', EXPIRED: 'Accesso scaduto. Riprova.', OTHER_APP: 'Accesso non riuscito. Riprova.', CODE_INVALID: 'Codice non valido o scaduto. Chiedine uno nuovo.', generic: 'Non è andata a buon fine. Riprova tra qualche secondo.', offline: 'Connessione non disponibile.', tooMany: 'Troppi tentativi: aspetta un minuto e riprova.', invalidEmail: 'Email non valida: controlla che sia scritta per intero, senza spazi.', detail: 'Dettaglio per l’assistenza' },
  },
  es: {
    title: 'Mi credencial',
    orgTitle: 'Su organización',
    orgIntro: 'Escriba la dirección de la consola de su empresa (la que abre en el navegador para acceder); está en el correo de bienvenida o puede pedirla a recursos humanos.',
    orgLabel: 'Dirección', orgExample: 'p. ej. https://empresa.ejemplo.es',
    orgNext: 'Continuar',
    orgInvalid: 'Dirección no válida: debe empezar por https:// o ser del tipo empresa.ejemplo.es.',
    orgUnreachable: 'No encuentro una organización en esta dirección. Revísela e inténtelo de nuevo.',
    emailIntro: 'Active la credencial con su correo de trabajo: le enviamos un código.',
    email: 'Correo de trabajo',
    send: 'Enviarme el código',
    sent: 'Si la dirección está registrada, recibirá un código de 6 cifras en un minuto. Revise también el spam.',
    code: 'Código recibido',
    activate: 'Activar la credencial',
    changeEmail: 'Cambiar correo',
    changeOrg: 'Cambiar organización',
    hint: 'Muestre el QR al lector de la puerta. Cambia cada 30 segundos: fotos y capturas no funcionan.',
    next: 'Nuevo código en {n} s',
    remove: 'Quitar la credencial de este teléfono',
    removeTitle: '¿Quitar la credencial?',
    removeText: 'Para usarla de nuevo tendrá que pedir un código nuevo por correo.',
    removeConfirm: 'Quitar',
    cancel: 'Cancelar',
    nfcReady: 'O acerque la parte trasera del teléfono al lector, como una tarjeta.',
    nfcOff: 'Para usar el teléfono como tarjeta active el NFC.',
    nfcOpen: 'Activar NFC',
    nfcDevBuild: 'El teléfono como tarjeta NFC funciona en la aplicación instalada, no en Expo Go.',
    ssoSignIn: 'Acceder con {provider}', ssoOr: 'o reciba un código por correo', ssoHint: 'Use la cuenta de la empresa con la que entra en Outlook, Teams o Gmail.',
    activated: 'Credencial activa en este teléfono.', loading: 'Cargando…',
    clock: 'La hora del teléfono parece incorrecta: active fecha y hora automáticas o el lector rechazará el QR.',
    parcels: { one: 'Tiene un paquete en recepción', many: 'Tiene {n} paquetes en recepción', today: '{site} · llegó a las {time}', day: '{site} · llegó el {date}', pieces: '{n} bultos' },
    settings: { open: 'Ajustes', title: 'Ajustes', back: 'Atrás', org: 'Organización', person: 'A nombre de', address: 'Dirección', removeIntro: 'Quite la credencial si cambia de teléfono o lo devuelve. Deja de funcionar enseguida, también en el servidor.', locked: 'Su organización gestiona la credencial desde la consola. Si cambia o pierde el teléfono, pida al administrador que la desactive.', revoked: 'Esta credencial ya no es válida: se desactivó desde la consola. Quítela de aquí y actívela de nuevo.', offline: 'No consigo contactar con el servidor. Inténtelo de nuevo cuando tenga conexión.', retry: 'Reintentar', SELF_REMOVE_DISABLED: 'Su organización ya no permite quitar la credencial desde aquí: pregunte al administrador.' },
    stale: { title: 'Esta credencial ya no es válida', text: 'Se activó en otro dispositivo o se desactivó desde la consola, y el lector de la puerta la rechaza. Actívela de nuevo en este teléfono.', old: 'Esta credencial se activó con una versión anterior: para paquetes e invitaciones actívela de nuevo.', action: 'Activar de nuevo', offline: 'No consigo contactar con el servidor: paquetes e invitaciones podrían no estar al día. El QR funciona igualmente.' },
    portal: { title: 'Sus apps', badge: 'Credencial', home: 'Inicio', invites: 'Invitaciones', invitesDetail: 'Visitas previstas y nuevas invitaciones', parcels: 'Paquetes', parcelsNone: 'Nada que recoger', parcelsSome: '{n} por recoger', noBadge: 'La credencial para las puertas no está activa para usted. Las demás apps de su organización están en la barra de abajo.', parcelsEmpty: 'No hay paquetes por recoger. Cuando llegue uno recibirá un aviso.' },
    parking: { title: 'Aparcamiento', tile: 'Aparcamiento', tileDetail: 'Sus días y reservas', fixed: 'Su plaza fija: {spot}', fixedHint: 'Cada lunes se le reserva toda la semana siguiente. Si un día no viene, libérela: la puede usar un compañero.', userHint: 'Reserve los días que necesite, como máximo {n} a la vez. La semana siguiente se abre el jueves.', opens: 'La semana próxima se abre el {date}.', active: 'Reservas activas: {n} de {max}', book: 'Reservar', free: '{n} libres', full: 'Completo', notOpen: 'Se abre el jueves', spot: 'Plaza {spot}', auto: 'fija', release: 'Liberar', cancel: 'Anular', releaseTitle: '¿Liberar la plaza?', releaseText: 'La plaza queda libre para sus compañeros.', today: 'Hoy', tomorrow: 'Mañana', none: 'No hay plazas configuradas: pregunte al administrador.', booked: 'Reservado: plaza {spot}.', pick: 'Elija los días', pickHint: 'Toque los días que necesite y luego elija la plaza. Toque un día ya reservado para liberarlo.', thisWeek: 'Esta semana', nextWeek: 'Semana próxima', spotTitle: 'Plaza', anySpot: 'La primera libre', anySpotHint: 'Asignada automáticamente, día a día.', noCommonSpot: 'Ninguna plaza está libre todos los días elegidos: reserve con la primera libre.', bookOne: 'Reservar 1 día', bookMany: 'Reservar {n} días', clear: 'Quitar selección', bookedDays: 'Reservado: {list}.', dayOn: '{day}, plaza {spot}', failedDay: '{day}: {reason}', leftOne: 'Puede reservar 1 día más.', leftMany: 'Puede reservar {n} días más.', closed: 'Cerrado', selected: 'seleccionado', errors: { PARKING_SPOT_TAKEN: 'Esa plaza ya está ocupada ese día.', PARKING_SPOT_NOT_FOUND: 'Esa plaza ya no está disponible.', PARKING_LIMIT: 'Ya tiene 4 reservas activas: anule una para reservar otro día.', PARKING_FULL: 'Ese día está todo ocupado.', PARKING_ALREADY_BOOKED: 'Ya tiene plaza ese día.', PARKING_DAY_CLOSED: 'Ese día todavía no se puede reservar.', PARKING_DAY_PAST: 'Ese día ya pasó.', NO_PARKING: 'El aparcamiento no está activo para usted.', APP_DISABLED: 'El aparcamiento no está activo en su organización.' } },
    invites: {
      open: 'Mis invitaciones', title: 'Invitaciones', back: 'Atrás', new: 'Nueva invitación', none: 'No espera a nadie. Cree una invitación: el invitado recibe un correo con un QR y en recepción toca «Tengo una invitación».',
      today: 'Hoy', tomorrow: 'Mañana', refresh: 'Actualizar',
      guest: 'Invitado', firstName: 'Nombre', lastName: 'Apellidos', company: 'Empresa (opcional)', email: 'Correo del invitado',
      when: 'Cuándo', day: 'Día', time: 'Hora', timeHint: 'Por ejemplo 9:30', site: 'Sede', purpose: 'Motivo',
      create: 'Crear invitación', created: 'Invitación creada.',
      emailSent: 'El invitado recibe un correo con el QR. También puede enviarle usted el código.',
      emailOff: 'El envío de correo no está activo: envíe usted el código al invitado.',
      code: 'Código', share: 'Compartir con el invitado', copied: 'Texto copiado: péguelo en un mensaje.', cancel: 'Cancelar invitación', cancelTitle: '¿Cancelar la invitación?', cancelText: 'El código deja de funcionar. Si el invitado ya tiene el correo, avísele usted.', cancelConfirm: 'Cancelar invitación', keep: 'Mantener',
      status: { PENDING: 'Esperado', USED: 'Llegó', CANCELLED: 'Cancelada', EXPIRED: 'No llegó' },
      purposes: { MEETING: 'Reunión', INTERVIEW: 'Entrevista', SUPPLIER: 'Proveedor', MAINTENANCE: 'Mantenimiento', DELIVERY: 'Entrega', OTHER: 'Otro' },
      shareText: 'Hola {firstName}, le espero {when} en {organisation}, sede de {site}. Al llegar toque «Tengo una invitación» en la tableta de recepción y muestre el QR del correo, o escriba el código {code}. Hasta pronto, {host}',
      push: { label: 'Avisarme cuando llegue una visita', hint: 'Una notificación en este teléfono cuando una visita suya se registre en la tableta de recepción.', denied: 'El navegador bloquea las notificaciones de este sitio: desbloquéelas en los ajustes del sitio y vuelva a intentarlo.', unsupported: 'Este navegador no recibe notificaciones de páginas web. Pruebe con Chrome o use la app Mi credencial.', ios: 'En iPhone las notificaciones solo llegan desde la pantalla de inicio: toque Compartir → Añadir a pantalla de inicio, abra la credencial desde ahí y actívelas.', test: 'Enviar una prueba', testSent: 'Prueba enviada: llega en unos segundos.' },
      reactivate: 'Para invitar desde aquí, quite la credencial y actívela de nuevo: solo una vez.',
      errors: { BAD_RESPONSE: 'El servidor ha respondido de forma inesperada. Revise la dirección de la organización y la conexión, y vuelva a intentarlo.', name: 'Escriba nombre y apellidos, solo letras.', email: 'Correo no válido.', time: 'Hora no válida: por ejemplo 9:30.', INVITATION_IN_PAST: 'Ese día ya ha pasado.', INVITATION_TOO_FAR: 'Puede invitar hasta 90 días antes.', NOT_A_HOST: 'Ya no está entre las personas a visitar: pregunte en recepción.', NOT_A_HOST_HERE: 'En esta sede no recibe visitas.', INVITATION_USED: 'El invitado ya llegó.', INVITATION_CANCELLED: 'Invitación ya cancelada.', INVITATION_EXPIRED: 'Invitación caducada.' },
    },
    errors: { CANCELLED: 'Acceso cancelado.', NO_EMPLOYEE: 'Su cuenta de empresa no figura entre los empleados con credencial: pregunte a recursos humanos.', OTHER_DIRECTORY: 'Ha usado la cuenta de otra organización.', WRONG_ISSUER: 'Ha usado la cuenta de otra organización.', NOT_A_WORK_ACCOUNT: 'Se necesita la cuenta de trabajo, no una personal.', PROVIDER_REFUSED: 'Se rechazó el acceso. Inténtelo de nuevo; si vuelve a pasar, pregunte a IT.', PROVIDER_UNREACHABLE: 'El servicio de acceso no responde. Inténtelo en un momento.', SSO_NOT_CONFIGURED: 'Su organización no ha activado el acceso con la cuenta de empresa: use el código por correo.', EXPIRED: 'Acceso caducado. Inténtelo de nuevo.', OTHER_APP: 'No se pudo acceder. Inténtelo de nuevo.', CODE_INVALID: 'Código no válido o caducado. Pida uno nuevo.', generic: 'No ha funcionado. Inténtelo de nuevo en unos segundos.', offline: 'Sin conexión.', tooMany: 'Demasiados intentos: espere un minuto y vuelva a intentarlo.', invalidEmail: 'Correo no válido: compruebe que esté completo y sin espacios.', detail: 'Detalle para soporte' },
  },
  en: {
    title: 'My badge',
    orgTitle: 'Your organisation',
    orgIntro: 'Type the address of your company’s console (the one you open in the browser to sign in); it is in your welcome email, or ask HR.',
    orgLabel: 'Address', orgExample: 'e.g. https://company.example.com',
    orgNext: 'Continue',
    orgInvalid: 'Invalid address: it must start with https:// or look like company.example.com.',
    orgUnreachable: 'No organisation found at this address. Check it and try again.',
    emailIntro: 'Activate the badge with your work email: we will send you a code.',
    email: 'Work email',
    send: 'Send me the code',
    sent: 'If the address is registered, you will receive a 6-digit code within a minute. Check your spam folder too.',
    code: 'Code received',
    activate: 'Activate badge',
    changeEmail: 'Change email',
    changeOrg: 'Change organisation',
    hint: 'Show the QR to the door reader. It changes every 30 seconds: photos and screenshots do not work.',
    next: 'New code in {n} s',
    remove: 'Remove the badge from this phone',
    removeTitle: 'Remove the badge?',
    removeText: 'To use it again you will need a new code by email.',
    removeConfirm: 'Remove',
    cancel: 'Cancel',
    nfcReady: 'Or hold the back of the phone to the reader, like a card.',
    nfcOff: 'Turn on NFC to use the phone as a card.',
    nfcOpen: 'Turn on NFC',
    nfcDevBuild: 'The phone works as an NFC card in the installed app, not in Expo Go.',
    ssoSignIn: 'Sign in with {provider}', ssoOr: 'or get a code by email', ssoHint: 'Use the work account you sign in to Outlook, Teams or Gmail with.',
    activated: 'Badge active on this phone.', loading: 'Loading…',
    clock: 'The phone clock looks wrong: turn on automatic date and time, or the reader will refuse the QR.',
    parcels: { one: 'A parcel is waiting for you at reception', many: '{n} parcels are waiting for you at reception', today: '{site} · arrived at {time}', day: '{site} · arrived on {date}', pieces: '{n} pieces' },
    settings: { open: 'Settings', title: 'Settings', back: 'Back', org: 'Organisation', person: 'Issued to', address: 'Address', removeIntro: 'Remove the badge if you change phone or hand it back. It stops working at once, on the server too.', locked: 'Your organisation manages the badge from its console. If you change or lose your phone, ask the administrator to turn it off.', revoked: 'This badge is no longer valid: it was turned off from the console. Remove it here and activate it again.', offline: 'Can’t reach the server. Try again when you’re online.', retry: 'Try again', SELF_REMOVE_DISABLED: 'Your organisation no longer lets you remove the badge here: ask the administrator.' },
    stale: { title: 'This badge is no longer valid', text: 'It was activated on another device or turned off from the console, and the door reader refuses it. Activate it again on this phone.', old: 'This badge was activated with an earlier version: activate it again for parcels and invitations.', action: 'Activate again', offline: 'Can’t reach the server: parcels and invitations may be out of date. The QR still works.' },
    portal: { title: 'Your apps', badge: 'Badge', home: 'Home', invites: 'Invitations', invitesDetail: 'Expected guests and new invitations', parcels: 'Parcels', parcelsNone: 'Nothing to collect', parcelsSome: '{n} to collect', noBadge: 'The door badge is not on for you. The other apps of your organisation are in the bar at the bottom.', parcelsEmpty: 'No parcels to collect. You get a notice when one arrives.' },
    parking: { title: 'Parking', tile: 'Parking', tileDetail: 'Your days and bookings', fixed: 'Your fixed spot: {spot}', fixedHint: 'Every Monday it is booked for you for the whole week after. If you are not coming one day, release it: a colleague can take it.', userHint: 'Book the days you need, at most {n} at a time. The week after opens on Thursday.', opens: 'Next week opens on {date}.', active: 'Active bookings: {n} of {max}', book: 'Book', free: '{n} free', full: 'Full', notOpen: 'Opens Thursday', spot: 'Spot {spot}', auto: 'fixed', release: 'Release', cancel: 'Cancel', releaseTitle: 'Release the spot?', releaseText: 'The spot becomes free for your colleagues.', today: 'Today', tomorrow: 'Tomorrow', none: 'No parking spots set up yet: ask the administrator.', booked: 'Booked: spot {spot}.', pick: 'Pick the days', pickHint: 'Tap the days you need, then choose the spot. Tap a day you have booked to release it.', thisWeek: 'This week', nextWeek: 'Next week', spotTitle: 'Spot', anySpot: 'First free spot', anySpotHint: 'Assigned automatically, day by day.', noCommonSpot: 'No spot is free on all the days you picked: book with the first free spot.', bookOne: 'Book 1 day', bookMany: 'Book {n} days', clear: 'Clear selection', bookedDays: 'Booked: {list}.', dayOn: '{day}, spot {spot}', failedDay: '{day}: {reason}', leftOne: 'You can book 1 more day.', leftMany: 'You can book {n} more days.', closed: 'Closed', selected: 'selected', errors: { PARKING_SPOT_TAKEN: 'That spot is already taken that day.', PARKING_SPOT_NOT_FOUND: 'That spot is no longer available.', PARKING_LIMIT: 'You already have 4 active bookings: cancel one to book another day.', PARKING_FULL: 'That day is fully booked.', PARKING_ALREADY_BOOKED: 'You already have a spot that day.', PARKING_DAY_CLOSED: 'That day cannot be booked yet.', PARKING_DAY_PAST: 'That day has passed.', NO_PARKING: 'Parking is not on for you.', APP_DISABLED: 'Parking is not on for your organisation.' } },
    invites: {
      open: 'My invitations', title: 'Invitations', back: 'Back', new: 'New invitation', none: 'No guests expected. Create an invitation: the guest receives an email with a QR and taps “I have an invitation” at reception.',
      today: 'Today', tomorrow: 'Tomorrow', refresh: 'Refresh',
      guest: 'Guest', firstName: 'First name', lastName: 'Last name', company: 'Company (optional)', email: 'Guest’s email',
      when: 'When', day: 'Day', time: 'Time', timeHint: 'For example 9:30', site: 'Site', purpose: 'Reason',
      create: 'Create invitation', created: 'Invitation created.',
      emailSent: 'The guest receives an email with the QR. You can also send them the code yourself.',
      emailOff: 'Email is not enabled: send the code to your guest yourself.',
      code: 'Code', share: 'Share with the guest', copied: 'Text copied: paste it into a message.', cancel: 'Cancel invitation', cancelTitle: 'Cancel the invitation?', cancelText: 'The code stops working. If the guest already has the email, let them know.', cancelConfirm: 'Cancel invitation', keep: 'Keep',
      status: { PENDING: 'Expected', USED: 'Arrived', CANCELLED: 'Cancelled', EXPIRED: 'Did not come' },
      purposes: { MEETING: 'Meeting', INTERVIEW: 'Interview', SUPPLIER: 'Supplier', MAINTENANCE: 'Maintenance', DELIVERY: 'Delivery', OTHER: 'Other' },
      shareText: 'Hi {firstName}, I’m expecting you {when} at {organisation}, {site} site. When you arrive, tap “I have an invitation” on the reception tablet and show the QR from the email, or type the code {code}. See you soon, {host}',
      push: { label: 'Tell me when a guest arrives', hint: 'A notification on this phone when one of your guests checks in at the reception tablet.', denied: 'The browser blocks notifications from this site: unblock them in the site settings, then try again.', unsupported: 'This browser cannot receive notifications from web pages. Try Chrome, or use the My badge app.', ios: 'On iPhone notifications only work from the Home Screen: tap Share → Add to Home Screen, open the badge from there and turn them on.', test: 'Send a test', testSent: 'Test sent: it arrives in a few seconds.' },
      reactivate: 'To invite guests from here, remove the badge and activate it again: only once.',
      errors: { BAD_RESPONSE: 'The server gave an unexpected answer. Check the organisation address and your connection, then try again.', name: 'Type first and last name, letters only.', email: 'Invalid email.', time: 'Invalid time: for example 9:30.', INVITATION_IN_PAST: 'That day has already passed.', INVITATION_TOO_FAR: 'You can invite up to 90 days ahead.', NOT_A_HOST: 'You are no longer among the people to visit: ask reception.', NOT_A_HOST_HERE: 'You do not receive visits at this site.', INVITATION_USED: 'The guest has already arrived.', INVITATION_CANCELLED: 'Invitation already cancelled.', INVITATION_EXPIRED: 'Invitation expired.' },
    },
    errors: { CANCELLED: 'Sign-in cancelled.', NO_EMPLOYEE: 'Your work account is not among the employees with a badge: ask HR.', OTHER_DIRECTORY: 'You used an account from another organisation.', WRONG_ISSUER: 'You used an account from another organisation.', NOT_A_WORK_ACCOUNT: 'A work account is needed, not a personal one.', PROVIDER_REFUSED: 'The sign-in was refused. Try again; if it happens again, ask IT.', PROVIDER_UNREACHABLE: 'The sign-in service is not answering. Try again in a moment.', SSO_NOT_CONFIGURED: 'Your organisation has not turned on work-account sign-in: use the email code.', EXPIRED: 'Sign-in expired. Try again.', OTHER_APP: 'Sign-in failed. Try again.', CODE_INVALID: 'Invalid or expired code. Ask for a new one.', generic: 'That didn’t work. Try again in a few seconds.', offline: 'No connection.', tooMany: 'Too many attempts: wait a minute and try again.', invalidEmail: 'Invalid email: check it is complete and has no spaces.', detail: 'Detail for support' },
  },
} as const;

export type Lang = keyof typeof STRINGS;
/** From the browser language: it, es, otherwise en. */
export const lang: Lang = (['it', 'es'] as const).find((l) => navigator.language.toLowerCase().startsWith(l)) ?? 'en';
export const t = STRINGS[lang];
export const intlLocale = lang === 'en' ? 'en-GB' : lang;
