export type Locale = 'it' | 'es' | 'en';
export const LOCALE_NAMES: Record<Locale, string> = { it: 'Italiano', es: 'Español', en: 'English' };

const it = {
  welcome: 'Benvenuti',
  welcomeSub: 'Registra il tuo ingresso o la tua uscita.',
  checkIn: 'Sto entrando',
  checkInSub: 'Prima volta oggi in sede',
  checkOut: 'Sto uscendo',
  checkOutSub: 'Chiudi la tua visita',
  steps: ['I tuoi dati', 'Informativa', 'Foto', 'Firma', 'Documenti'],
  stepOf: 'Passo {n} di {total}',
  firstName: 'Nome', lastName: 'Cognome', company: 'Azienda', companyHint: 'Facoltativo',
  email: 'Email', emailHint: 'Facoltativa: ti inviamo il badge di uscita e, se lo chiedi, l’informativa privacy',
  host: 'Chi incontri', hostHint: 'Nome della persona che ti aspetta',
  hostPlaceholder: 'Scegli la persona', hostPickHint: 'Apri il menu e scegli la persona che ti aspetta',
  distance: 'Quanta strada hai fatto per arrivare in sede?',
  distances: { UNDER_10_KM: 'Meno di 10 km', FROM_10_TO_100_KM: 'Tra 10 e 100 km', OVER_100_KM: 'Più di 100 km' },
  purpose: 'Motivo della visita',
  purposes: { MEETING: 'Riunione', INTERVIEW: 'Colloquio', SUPPLIER: 'Fornitore', MAINTENANCE: 'Manutenzione', DELIVERY: 'Consegna', OTHER: 'Altro' },
  documentType: 'Documento di identità', documentNumber: 'Numero del documento',
  documentTypes: { ID_CARD: 'Carta d’identità', PASSPORT: 'Passaporto', DRIVING_LICENSE: 'Patente', OTHER: 'Altro' },
  next: 'Continua', back: 'Indietro', cancel: 'Annulla',
  noticeRead: 'Ho letto l’informativa privacy',
  sendNotice: 'Inviamela anche via email',
  noticeScroll: 'Scorri fino in fondo per continuare',
  docsTitle: 'Documenti da accettare', docsHint: 'Leggi ogni documento fino in fondo e conferma.', docAccept: 'Ho letto e accetto', signHintDocs: 'Firmando confermi che i dati sono corretti, di aver ricevuto l’informativa e di accettare i documenti letti.',
  photoDocTitle: 'Foto del documento', photoDocHint: 'Inquadra solo il documento, su una superficie piana.',
  photoAssetTitle: 'Numero di serie del computer', photoAssetHint: 'Fotografa l’etichetta con il numero di serie del portatile che porti con te.',
  takePhoto: 'Scatta la foto', retakePhoto: 'Rifai la foto',
  signTitle: 'Firma qui', signHint: 'Firmando confermi che i dati sono corretti e di aver ricevuto l’informativa.',
  clear: 'Cancella firma', confirmCheckIn: 'Registra il mio ingresso',
  doneTitle: 'Registrazione completata',
  doneCode: 'Il tuo codice di uscita',
  doneHint: 'Tienilo a mente: ti servirà per uscire. La reception ti consegnerà il badge.',
  doneEmail: 'Ti stiamo inviando l’informativa via email.',
  doneBadgeEmail: 'Ti stiamo inviando il badge di uscita via email.',
  doneHostNotified: 'Stiamo avvisando via email la persona che incontri.',
  finish: 'Fine',
  invite: 'Ho un invito', inviteSub: 'Hai ricevuto un QR via email', inviteTitle: 'Mostra il QR del tuo invito', inviteHint: 'Avvicina alla fotocamera il QR ricevuto via email.', inviteWrong: 'Questo non è il QR di un invito. Usa quello dell’email di invito.', inviteType: 'Oppure scrivi il codice dell’invito', inviteCode: 'Codice invito', inviteFind: 'Cerca', inviteNoInvite: 'Registrati senza invito', inviteHello: 'Ciao {name}, ti stavamo aspettando.', inviteCheck: 'Controlla i tuoi dati e completa quelli mancanti.',
  outTitle: 'Chi sta uscendo?',
  outHint: 'Mostra il QR del tuo badge, oppure scrivi il codice o le prime lettere del cognome.',
  scanTitle: 'Inquadra il QR del badge', scanOr: 'oppure', scanHint: 'Avvicina alla fotocamera del tablet il QR ricevuto via email o fotografato all’ingresso.', scanWrong: 'Questo QR non è un badge di uscita. Mostra quello ricevuto all’ingresso.', scanStop: 'Scrivi il codice', scanNoCamera: 'Fotocamera non disponibile: scrivi il codice o il cognome.',
  doneQr: 'Fotografa questo QR: all’uscita basta mostrarlo al tablet.',
  outSearch: 'Codice o cognome',
  outNone: 'Nessuna visita aperta trovata. Controlla il codice o chiedi alla reception.',
  outConfirm: 'Conferma uscita',
  outDone: 'Uscita registrata, buona giornata.',
  inAt: 'Entrato alle',
  sending: 'Invio in corso…',
  required: 'Campo obbligatorio',
  invalidEmail: 'Indirizzo email non valido',
  invalidName: 'Usa solo lettere, spazi, apostrofi e trattini',
  errors: {
    generic: 'Non è andata a buon fine. Riprova, e se succede di nuovo chiedi alla reception.',
    NOTICE_OUTDATED: 'L’informativa è stata aggiornata. Leggi la nuova versione e firma di nuovo.',
    DOCUMENTS_OUTDATED: 'Un documento è stato aggiornato. Leggi la nuova versione e firma di nuovo.',
    VISIT_ALREADY_CLOSED: 'La tua uscita è già registrata: puoi andare.',
    INVITATION_NOT_FOUND: 'Invito non trovato o annullato. Puoi registrarti senza invito.',
    INVITATION_USED: 'Con questo invito qualcuno è già entrato oggi. Chiedi alla reception.',
    INVITATION_NOT_TODAY: 'Questo invito non è per oggi. Controlla la data nell’email o registrati senza invito.',
    INVITATION_OTHER_SITE: 'Questo invito è per un’altra sede: controlla l’indirizzo nell’email.',
    offline: 'Il tablet non è connesso a internet. Chiedi alla reception.',
  },
  privacyFooter: 'Cifriamo i tuoi dati e li cancelliamo da soli quando scade il periodo previsto.',
  preHello: 'Ciao {name}, la registrazione dal telefono è completa.', preHint: 'Non devi compilare altro: registra l’ingresso e ricevi il badge di uscita.', preAsset: 'Manca solo la foto del numero di serie del computer.',
  guestTitle: 'Registrati prima di arrivare', guestWhen: 'Ti aspettiamo {when} a {site}.', guestHost: 'Ti incontra {host}.', guestHint: 'Bastano un paio di minuti: in reception poi mostri solo il QR dell’email.',
  guestAlready: 'Hai già inviato la registrazione. Se qualcosa è cambiato puoi correggerla fino al tuo arrivo.', guestSubmit: 'Invia la registrazione',
  guestDoneTitle: 'Registrazione inviata', guestDoneText: 'All’arrivo tocca “Ho un invito” sul tablet della reception e mostra il QR dell’email: registriamo l’ingresso senza farti compilare altro.', guestEdit: 'Correggi la registrazione',
  guestNoCode: 'Apri questa pagina dal link nell’email di invito.', guestExpired: 'Il giorno di questo invito è passato.', guestNotFound: 'Invito non trovato o annullato. Controlla il link nell’email o chiedi a chi ti ha invitato.', guestUsed: 'Con questo invito l’ingresso è già registrato.',
};

type Dict = typeof it;

const es: Dict = {
  welcome: 'Le damos la bienvenida',
  welcomeSub: 'Registre su entrada o su salida.',
  checkIn: 'Estoy entrando', checkInSub: 'Primera vez hoy en la sede',
  checkOut: 'Estoy saliendo', checkOutSub: 'Cierre su visita',
  steps: ['Sus datos', 'Información', 'Fotos', 'Firma', 'Documentos'],
  stepOf: 'Paso {n} de {total}',
  firstName: 'Nombre', lastName: 'Apellidos', company: 'Empresa', companyHint: 'Opcional',
  email: 'Correo electrónico', emailHint: 'Opcional: le enviamos la credencial de salida y, si lo pide, la información sobre privacidad',
  host: 'A quién visita', hostHint: 'Nombre de la persona que le espera',
  hostPlaceholder: 'Elija a la persona', hostPickHint: 'Abra el menú y elija a la persona que le espera',
  distance: '¿Qué distancia ha recorrido para llegar a la sede?',
  distances: { UNDER_10_KM: 'Menos de 10 km', FROM_10_TO_100_KM: 'Entre 10 y 100 km', OVER_100_KM: 'Más de 100 km' },
  purpose: 'Motivo de la visita',
  purposes: { MEETING: 'Reunión', INTERVIEW: 'Entrevista', SUPPLIER: 'Proveedor', MAINTENANCE: 'Mantenimiento', DELIVERY: 'Entrega', OTHER: 'Otro' },
  documentType: 'Documento de identidad', documentNumber: 'Número de documento',
  documentTypes: { ID_CARD: 'DNI / Cédula', PASSPORT: 'Pasaporte', DRIVING_LICENSE: 'Licencia de conducir', OTHER: 'Otro' },
  next: 'Continuar', back: 'Atrás', cancel: 'Cancelar',
  noticeRead: 'He leído la información sobre privacidad',
  sendNotice: 'Enviármela también por correo',
  noticeScroll: 'Desplácese hasta el final para continuar',
  docsTitle: 'Documentos que aceptar', docsHint: 'Lea cada documento hasta el final y confirme.', docAccept: 'He leído y acepto', signHintDocs: 'Al firmar confirma que sus datos son correctos, que ha recibido la información sobre privacidad y que acepta los documentos leídos.',
  photoDocTitle: 'Foto del documento', photoDocHint: 'Encuadre solo el documento, sobre una superficie plana.',
  photoAssetTitle: 'Número de serie del portátil', photoAssetHint: 'Fotografíe la etiqueta con el número de serie del portátil que trae.',
  takePhoto: 'Tomar la foto', retakePhoto: 'Repetir la foto',
  signTitle: 'Firme aquí', signHint: 'Al firmar confirma que sus datos son correctos y que ha recibido la información sobre privacidad.',
  clear: 'Borrar firma', confirmCheckIn: 'Registrar mi entrada',
  doneTitle: 'Registro completado',
  doneCode: 'Su código de salida',
  doneHint: 'Guárdelo: lo necesitará para salir. Recepción le entregará la credencial.',
  doneEmail: 'Le estamos enviando la información por correo.',
  doneBadgeEmail: 'Le estamos enviando la credencial de salida por correo.',
  doneHostNotified: 'Estamos avisando por correo a la persona que visita.',
  finish: 'Terminar',
  invite: 'Tengo una invitación', inviteSub: 'Recibió un QR por correo', inviteTitle: 'Muestre el QR de su invitación', inviteHint: 'Acerque a la cámara el QR recibido por correo.', inviteWrong: 'Este no es el QR de una invitación. Use el del correo de invitación.', inviteType: 'O escriba el código de la invitación', inviteCode: 'Código de invitación', inviteFind: 'Buscar', inviteNoInvite: 'Registrarse sin invitación', inviteHello: 'Hola {name}, le estábamos esperando.', inviteCheck: 'Revise sus datos y complete los que faltan.',
  outTitle: '¿Quién sale?',
  outHint: 'Muestre el QR de su credencial, o escriba el código o las primeras letras del apellido.',
  scanTitle: 'Escanear el QR de la credencial', scanOr: 'o bien', scanHint: 'Acerque a la cámara de la tableta el QR recibido por correo o fotografiado al entrar.', scanWrong: 'Este QR no es una credencial de salida. Muestre el que recibió al entrar.', scanStop: 'Escribir el código', scanNoCamera: 'Cámara no disponible: escriba el código o el apellido.',
  doneQr: 'Fotografíe este QR: al salir basta con mostrarlo a la tableta.',
  outSearch: 'Código o apellido',
  outNone: 'No hay visitas abiertas con esos datos. Revise el código o consulte en recepción.',
  outConfirm: 'Confirmar salida',
  outDone: 'Salida registrada, que tenga un buen día.',
  inAt: 'Entró a las',
  sending: 'Enviando…',
  required: 'Campo obligatorio',
  invalidEmail: 'Correo electrónico no válido',
  invalidName: 'Use solo letras, espacios, apóstrofos y guiones',
  errors: {
    generic: 'No ha funcionado. Inténtelo de nuevo y, si vuelve a pasar, pregunte en recepción.',
    NOTICE_OUTDATED: 'La información sobre privacidad se ha actualizado. Lea la nueva versión y firme de nuevo.',
    DOCUMENTS_OUTDATED: 'Se ha actualizado un documento. Lea la nueva versión y firme de nuevo.',
    VISIT_ALREADY_CLOSED: 'Su salida ya está registrada: puede irse.',
    INVITATION_NOT_FOUND: 'Invitación no encontrada o anulada. Puede registrarse sin invitación.',
    INVITATION_USED: 'Alguien ya ha entrado hoy con esta invitación. Pregunte en recepción.',
    INVITATION_NOT_TODAY: 'Esta invitación no es para hoy. Revise la fecha en el correo o regístrese sin invitación.',
    INVITATION_OTHER_SITE: 'Esta invitación es para otra sede: revise la dirección en el correo.',
    offline: 'La tableta no tiene conexión. Solicite ayuda en recepción.',
  },
  privacyFooter: 'Ciframos sus datos y los borramos solos cuando vence el plazo previsto.',
  preHello: 'Hola {name}, el registro desde el teléfono está completo.', preHint: 'No tiene que rellenar nada más: registre la entrada y reciba la credencial de salida.', preAsset: 'Solo falta la foto del número de serie del ordenador.',
  guestTitle: 'Regístrese antes de llegar', guestWhen: 'Le esperamos {when} en {site}.', guestHost: 'Le recibe {host}.', guestHint: 'Son un par de minutos: en recepción solo tendrá que mostrar el QR del correo.',
  guestAlready: 'Ya envió el registro. Si algo ha cambiado puede corregirlo hasta su llegada.', guestSubmit: 'Enviar el registro',
  guestDoneTitle: 'Registro enviado', guestDoneText: 'Al llegar, pulse «Tengo una invitación» en la tableta de recepción y muestre el QR del correo: registramos la entrada sin que tenga que rellenar nada más.', guestEdit: 'Corregir el registro',
  guestNoCode: 'Abra esta página desde el enlace del correo de invitación.', guestExpired: 'El día de esta invitación ya pasó.', guestNotFound: 'Invitación no encontrada o anulada. Revise el enlace del correo o pregunte a quien le invitó.', guestUsed: 'Con esta invitación la entrada ya está registrada.',
};

const en: Dict = {
  welcome: 'Welcome',
  welcomeSub: 'Sign in or sign out of the building.',
  checkIn: 'I’m arriving', checkInSub: 'First time on site today',
  checkOut: 'I’m leaving', checkOutSub: 'Close your visit',
  steps: ['Your details', 'Privacy notice', 'Photos', 'Signature', 'Documents'],
  stepOf: 'Step {n} of {total}',
  firstName: 'First name', lastName: 'Last name', company: 'Company', companyHint: 'Optional',
  email: 'Email', emailHint: 'Optional: we send you your exit badge and, if you ask, the privacy notice',
  host: 'Who are you meeting', hostHint: 'Name of the person expecting you',
  hostPlaceholder: 'Choose the person', hostPickHint: 'Open the menu and choose the person expecting you',
  distance: 'How far did you travel to get here?',
  distances: { UNDER_10_KM: 'Less than 10 km', FROM_10_TO_100_KM: 'Between 10 and 100 km', OVER_100_KM: 'More than 100 km' },
  purpose: 'Reason for your visit',
  purposes: { MEETING: 'Meeting', INTERVIEW: 'Interview', SUPPLIER: 'Supplier', MAINTENANCE: 'Maintenance', DELIVERY: 'Delivery', OTHER: 'Other' },
  documentType: 'Identity document', documentNumber: 'Document number',
  documentTypes: { ID_CARD: 'ID card', PASSPORT: 'Passport', DRIVING_LICENSE: 'Driving licence', OTHER: 'Other' },
  next: 'Continue', back: 'Back', cancel: 'Cancel',
  noticeRead: 'I have read the privacy notice',
  sendNotice: 'Also send it to my email',
  noticeScroll: 'Scroll to the end to continue',
  docsTitle: 'Documents to accept', docsHint: 'Read each document to the end and confirm.', docAccept: 'I have read and accept', signHintDocs: 'By signing you confirm your details are correct, that you received the privacy notice and that you accept the documents you read.',
  photoDocTitle: 'Photo of your document', photoDocHint: 'Frame only the document, on a flat surface.',
  photoAssetTitle: 'Laptop serial number', photoAssetHint: 'Take a photo of the serial-number label on the laptop you are bringing in.',
  takePhoto: 'Take photo', retakePhoto: 'Retake photo',
  signTitle: 'Sign here', signHint: 'By signing you confirm your details are correct and that you received the privacy notice.',
  clear: 'Clear signature', confirmCheckIn: 'Sign me in',
  doneTitle: 'You’re signed in',
  doneCode: 'Your sign-out code',
  doneHint: 'Keep it handy: you’ll need it to leave. Reception will give you your badge.',
  doneEmail: 'We’re emailing you the privacy notice.',
  doneBadgeEmail: 'We’re emailing you your exit badge.',
  doneHostNotified: 'We’re emailing the person you’re meeting to say you’re here.',
  finish: 'Done',
  invite: 'I have an invitation', inviteSub: 'You received a QR by email', inviteTitle: 'Show your invitation QR', inviteHint: 'Hold the QR you received by email up to the camera.', inviteWrong: 'This is not an invitation QR. Use the one in your invitation email.', inviteType: 'Or type the invitation code', inviteCode: 'Invitation code', inviteFind: 'Find', inviteNoInvite: 'Register without invitation', inviteHello: 'Hello {name}, we were expecting you.', inviteCheck: 'Check your details and fill in what is missing.',
  outTitle: 'Who is leaving?',
  outHint: 'Show the QR on your badge, or type the code or the first letters of your last name.',
  scanTitle: 'Scan your badge QR', scanOr: 'or', scanHint: 'Hold the QR you received by email or photographed on arrival up to the tablet camera.', scanWrong: 'This QR is not an exit badge. Show the one you received on arrival.', scanStop: 'Type the code', scanNoCamera: 'Camera not available: type the code or your last name.',
  doneQr: 'Take a photo of this QR: when leaving, just show it to the tablet.',
  outSearch: 'Code or last name',
  outNone: 'No open visit found. Check the code or ask reception.',
  outConfirm: 'Confirm sign-out',
  outDone: 'You’re signed out. Have a good day.',
  inAt: 'Arrived at',
  sending: 'Sending…',
  required: 'Required',
  invalidEmail: 'Invalid email address',
  invalidName: 'Use letters, spaces, apostrophes and hyphens only',
  errors: {
    generic: 'That didn’t work. Try again, and if it happens again ask reception.',
    NOTICE_OUTDATED: 'The privacy notice has been updated. Read the new version and sign again.',
    DOCUMENTS_OUTDATED: 'A document has been updated. Read the new version and sign again.',
    VISIT_ALREADY_CLOSED: 'You’re already signed out, so you can go.',
    INVITATION_NOT_FOUND: 'Invitation not found or cancelled. You can register without it.',
    INVITATION_USED: 'Someone has already signed in with this invitation. Ask reception.',
    INVITATION_NOT_TODAY: 'This invitation is not for today. Check the date in the email or register without it.',
    INVITATION_OTHER_SITE: 'This invitation is for another site: check the address in the email.',
    offline: 'The tablet is offline. Ask reception for help.',
  },
  privacyFooter: 'We encrypt your data and delete it on our own when its retention period ends.',
  preHello: 'Hi {name}, your registration from the phone is complete.', preHint: 'There’s nothing else to fill in: check in and get your exit badge.', preAsset: 'We only need a photo of your laptop’s serial number.',
  guestTitle: 'Register before you arrive', guestWhen: 'We’re expecting you {when} at {site}.', guestHost: 'You’re meeting {host}.', guestHint: 'It takes a couple of minutes: at reception you then just show the QR from the email.',
  guestAlready: 'You’ve already sent your registration. If something changed you can correct it until you arrive.', guestSubmit: 'Send registration',
  guestDoneTitle: 'Registration sent', guestDoneText: 'When you arrive, tap “I have an invitation” on the reception tablet and show the QR from the email: we check you in without asking anything else.', guestEdit: 'Correct my registration',
  guestNoCode: 'Open this page from the link in your invitation email.', guestExpired: 'The day of this invitation has passed.', guestNotFound: 'Invitation not found or cancelled. Check the link in the email or ask the person who invited you.', guestUsed: 'You have already checked in with this invitation.',
};

export const STRINGS: Record<Locale, Dict> = { it, es, en };
export type Strings = Dict;
