export type Locale = 'it' | 'es' | 'en';
export const LOCALE_NAMES: Record<Locale, string> = { it: 'Italiano', es: 'Español', en: 'English' };

const it = {
  welcome: 'Benvenuti',
  welcomeSub: 'Registra il tuo ingresso o la tua uscita.',
  checkIn: 'Sto entrando',
  checkInSub: 'Prima volta oggi in sede',
  checkOut: 'Sto uscendo',
  checkOutSub: 'Chiudi la tua visita',
  steps: ['I tuoi dati', 'Informativa', 'Foto', 'Firma'],
  stepOf: 'Passo {n} di {total}',
  firstName: 'Nome', lastName: 'Cognome', company: 'Azienda', companyHint: 'Facoltativo',
  email: 'Email', emailHint: 'Facoltativa: ti inviamo il badge di uscita e, se lo chiedi, l’informativa privacy',
  host: 'Chi incontri', hostHint: 'Nome della persona che ti aspetta',
  hostPlaceholder: 'Scegli la persona', hostPickHint: 'Apri il menu e scegli la persona che ti aspetta',
  distance: 'Quanta strada hai fatto per arrivare in sede?',
  distances: { UNDER_10_KM: 'Meno di 10 km', FROM_10_TO_100_KM: 'Tra 10 e 100 km', OVER_100_KM: 'Più di 100 km' },
  purpose: 'Motivo della visita',
  purposes: { MEETING: 'Riunione', INTERVIEW: 'Colloquio', SUPPLIER: 'Fornitore', MAINTENANCE: 'Manutenzione', DELIVERY: 'Consegna', OTHER: 'Altro' },
  documentType: 'Documento di identità', documentNumber: 'Numero del documento',
  documentTypes: { ID_CARD: 'Carta d’identità', PASSPORT: 'Passaporto', DRIVING_LICENSE: 'Patente', OTHER: 'Altro' },
  next: 'Continua', back: 'Indietro', cancel: 'Annulla',
  noticeRead: 'Ho letto l’informativa privacy',
  sendNotice: 'Inviamela anche via email',
  noticeScroll: 'Scorri fino in fondo per continuare',
  photoDocTitle: 'Foto del documento', photoDocHint: 'Inquadra solo il documento, su una superficie piana.',
  photoAssetTitle: 'Numero di serie del computer', photoAssetHint: 'Fotografa l’etichetta con il numero di serie del portatile che porti con te.',
  takePhoto: 'Scatta la foto', retakePhoto: 'Rifai la foto',
  signTitle: 'Firma qui', signHint: 'Firmando confermi che i dati sono corretti e di aver ricevuto l’informativa.',
  clear: 'Cancella firma', confirmCheckIn: 'Registra il mio ingresso',
  doneTitle: 'Registrazione completata',
  doneCode: 'Il tuo codice di uscita',
  doneHint: 'Tienilo a mente: ti servirà per uscire. La reception ti consegnerà il badge.',
  doneEmail: 'Ti abbiamo inviato l’informativa via email.',
  doneBadgeEmail: 'Ti abbiamo inviato il badge di uscita via email.',
  doneHostNotified: 'Abbiamo avvisato la persona che incontri: sta arrivando.',
  finish: 'Fine',
  outTitle: 'Chi sta uscendo?',
  outHint: 'Mostra il QR del tuo badge, oppure scrivi il codice o le prime lettere del cognome.',
  scanTitle: 'Inquadra il QR del badge', scanOr: 'oppure', scanHint: 'Avvicina alla fotocamera del tablet il QR ricevuto via email o fotografato all’ingresso.', scanWrong: 'Questo QR non è un badge di uscita. Mostra quello ricevuto all’ingresso.', scanStop: 'Scrivi il codice', scanNoCamera: 'Fotocamera non disponibile: scrivi il codice o il cognome.',
  doneQr: 'Fotografa questo QR: all’uscita basta mostrarlo al tablet.',
  outSearch: 'Codice o cognome',
  outNone: 'Nessuna visita aperta trovata. Controlla il codice o chiedi alla reception.',
  outConfirm: 'Conferma uscita',
  outDone: 'Uscita registrata. Buona giornata!',
  inAt: 'Entrato alle',
  sending: 'Invio in corso…',
  required: 'Campo obbligatorio',
  invalidEmail: 'Indirizzo email non valido',
  invalidName: 'Usa solo lettere, spazi, apostrofi e trattini',
  errors: {
    generic: 'Non è stato possibile completare l’operazione. Riprova o chiedi alla reception.',
    NOTICE_OUTDATED: 'L’informativa è stata aggiornata. Leggi la nuova versione e firma di nuovo.',
    VISIT_ALREADY_CLOSED: 'Questa visita risulta già chiusa.',
    offline: 'Il tablet non è connesso. Chiedi assistenza alla reception.',
  },
  privacyFooter: 'I tuoi dati sono cifrati e cancellati automaticamente alla scadenza prevista.',
};

type Dict = typeof it;

const es: Dict = {
  welcome: 'Le damos la bienvenida',
  welcomeSub: 'Registre su entrada o su salida.',
  checkIn: 'Estoy entrando', checkInSub: 'Primera vez hoy en la sede',
  checkOut: 'Estoy saliendo', checkOutSub: 'Cierre su visita',
  steps: ['Sus datos', 'Información', 'Fotos', 'Firma'],
  stepOf: 'Paso {n} de {total}',
  firstName: 'Nombre', lastName: 'Apellidos', company: 'Empresa', companyHint: 'Opcional',
  email: 'Correo electrónico', emailHint: 'Opcional: le enviamos la credencial de salida y, si lo pide, la información sobre privacidad',
  host: 'A quién visita', hostHint: 'Nombre de la persona que le espera',
  hostPlaceholder: 'Elija a la persona', hostPickHint: 'Abra el menú y elija a la persona que le espera',
  distance: '¿Qué distancia ha recorrido para llegar a la sede?',
  distances: { UNDER_10_KM: 'Menos de 10 km', FROM_10_TO_100_KM: 'Entre 10 y 100 km', OVER_100_KM: 'Más de 100 km' },
  purpose: 'Motivo de la visita',
  purposes: { MEETING: 'Reunión', INTERVIEW: 'Entrevista', SUPPLIER: 'Proveedor', MAINTENANCE: 'Mantenimiento', DELIVERY: 'Entrega', OTHER: 'Otro' },
  documentType: 'Documento de identidad', documentNumber: 'Número de documento',
  documentTypes: { ID_CARD: 'DNI / Cédula', PASSPORT: 'Pasaporte', DRIVING_LICENSE: 'Licencia de conducir', OTHER: 'Otro' },
  next: 'Continuar', back: 'Atrás', cancel: 'Cancelar',
  noticeRead: 'He leído la información sobre privacidad',
  sendNotice: 'Enviármela también por correo',
  noticeScroll: 'Desplácese hasta el final para continuar',
  photoDocTitle: 'Foto del documento', photoDocHint: 'Encuadre solo el documento, sobre una superficie plana.',
  photoAssetTitle: 'Número de serie del portátil', photoAssetHint: 'Fotografíe la etiqueta con el número de serie del portátil que trae.',
  takePhoto: 'Tomar la foto', retakePhoto: 'Repetir la foto',
  signTitle: 'Firme aquí', signHint: 'Al firmar confirma que sus datos son correctos y que ha recibido la información sobre privacidad.',
  clear: 'Borrar firma', confirmCheckIn: 'Registrar mi entrada',
  doneTitle: 'Registro completado',
  doneCode: 'Su código de salida',
  doneHint: 'Guárdelo: lo necesitará para salir. Recepción le entregará la credencial.',
  doneEmail: 'Le hemos enviado la información por correo.',
  doneBadgeEmail: 'Le hemos enviado la credencial de salida por correo.',
  doneHostNotified: 'Hemos avisado a la persona que visita: ya viene.',
  finish: 'Terminar',
  outTitle: '¿Quién sale?',
  outHint: 'Muestre el QR de su credencial, o escriba el código o las primeras letras del apellido.',
  scanTitle: 'Escanear el QR de la credencial', scanOr: 'o bien', scanHint: 'Acerque a la cámara de la tableta el QR recibido por correo o fotografiado al entrar.', scanWrong: 'Este QR no es una credencial de salida. Muestre el que recibió al entrar.', scanStop: 'Escribir el código', scanNoCamera: 'Cámara no disponible: escriba el código o el apellido.',
  doneQr: 'Fotografíe este QR: al salir basta con mostrarlo a la tableta.',
  outSearch: 'Código o apellido',
  outNone: 'No hay visitas abiertas con esos datos. Revise el código o consulte en recepción.',
  outConfirm: 'Confirmar salida',
  outDone: 'Salida registrada. ¡Que tenga un buen día!',
  inAt: 'Entró a las',
  sending: 'Enviando…',
  required: 'Campo obligatorio',
  invalidEmail: 'Correo electrónico no válido',
  invalidName: 'Use solo letras, espacios, apóstrofos y guiones',
  errors: {
    generic: 'No se pudo completar la operación. Inténtelo de nuevo o consulte en recepción.',
    NOTICE_OUTDATED: 'La información sobre privacidad se ha actualizado. Lea la nueva versión y firme de nuevo.',
    VISIT_ALREADY_CLOSED: 'Esta visita ya está cerrada.',
    offline: 'La tableta no tiene conexión. Solicite ayuda en recepción.',
  },
  privacyFooter: 'Sus datos se cifran y se eliminan automáticamente al vencer el plazo previsto.',
};

const en: Dict = {
  welcome: 'Welcome',
  welcomeSub: 'Sign in or sign out of the building.',
  checkIn: 'I’m arriving', checkInSub: 'First time on site today',
  checkOut: 'I’m leaving', checkOutSub: 'Close your visit',
  steps: ['Your details', 'Privacy notice', 'Photos', 'Signature'],
  stepOf: 'Step {n} of {total}',
  firstName: 'First name', lastName: 'Last name', company: 'Company', companyHint: 'Optional',
  email: 'Email', emailHint: 'Optional: we send you your exit badge and, if you ask, the privacy notice',
  host: 'Who are you meeting', hostHint: 'Name of the person expecting you',
  hostPlaceholder: 'Choose the person', hostPickHint: 'Open the menu and choose the person expecting you',
  distance: 'How far did you travel to get here?',
  distances: { UNDER_10_KM: 'Less than 10 km', FROM_10_TO_100_KM: 'Between 10 and 100 km', OVER_100_KM: 'More than 100 km' },
  purpose: 'Reason for your visit',
  purposes: { MEETING: 'Meeting', INTERVIEW: 'Interview', SUPPLIER: 'Supplier', MAINTENANCE: 'Maintenance', DELIVERY: 'Delivery', OTHER: 'Other' },
  documentType: 'Identity document', documentNumber: 'Document number',
  documentTypes: { ID_CARD: 'ID card', PASSPORT: 'Passport', DRIVING_LICENSE: 'Driving licence', OTHER: 'Other' },
  next: 'Continue', back: 'Back', cancel: 'Cancel',
  noticeRead: 'I have read the privacy notice',
  sendNotice: 'Also send it to my email',
  noticeScroll: 'Scroll to the end to continue',
  photoDocTitle: 'Photo of your document', photoDocHint: 'Frame only the document, on a flat surface.',
  photoAssetTitle: 'Laptop serial number', photoAssetHint: 'Take a photo of the serial-number label on the laptop you are bringing in.',
  takePhoto: 'Take photo', retakePhoto: 'Retake photo',
  signTitle: 'Sign here', signHint: 'By signing you confirm your details are correct and that you received the privacy notice.',
  clear: 'Clear signature', confirmCheckIn: 'Sign me in',
  doneTitle: 'You’re signed in',
  doneCode: 'Your sign-out code',
  doneHint: 'Keep it handy: you’ll need it to leave. Reception will give you your badge.',
  doneEmail: 'We’ve emailed you the privacy notice.',
  doneBadgeEmail: 'We’ve emailed you your exit badge.',
  doneHostNotified: 'We’ve let the person you’re meeting know you’re here.',
  finish: 'Done',
  outTitle: 'Who is leaving?',
  outHint: 'Show the QR on your badge, or type the code or the first letters of your last name.',
  scanTitle: 'Scan your badge QR', scanOr: 'or', scanHint: 'Hold the QR you received by email or photographed on arrival up to the tablet camera.', scanWrong: 'This QR is not an exit badge. Show the one you received on arrival.', scanStop: 'Type the code', scanNoCamera: 'Camera not available: type the code or your last name.',
  doneQr: 'Take a photo of this QR: when leaving, just show it to the tablet.',
  outSearch: 'Code or last name',
  outNone: 'No open visit found. Check the code or ask reception.',
  outConfirm: 'Confirm sign-out',
  outDone: 'You’re signed out. Have a good day!',
  inAt: 'Arrived at',
  sending: 'Sending…',
  required: 'Required',
  invalidEmail: 'Invalid email address',
  invalidName: 'Use letters, spaces, apostrophes and hyphens only',
  errors: {
    generic: 'The operation could not be completed. Try again or ask reception.',
    NOTICE_OUTDATED: 'The privacy notice has been updated. Read the new version and sign again.',
    VISIT_ALREADY_CLOSED: 'This visit is already closed.',
    offline: 'The tablet is offline. Please ask reception for help.',
  },
  privacyFooter: 'Your data is encrypted and deleted automatically when its retention period ends.',
};

export const STRINGS: Record<Locale, Dict> = { it, es, en };
export type Strings = Dict;
